### ISSUE TITLE
Post condition usage guide

### ISSUE THREAD

**Issue by agraebe** [hirosystems/docs#10]
[This issue](https://github.com/blockstack/stacks-wallet-web/issues/1700) surfaces the lack of guidance around the usage of post conditions. So far, we documented only the concept in the Stacks documentation: https://docs.stacks.co/understand-stacks/transactions#post-conditions

_Note: While this is a gap in our docs, it should be carefully reviewed what priority this should be assigned_

**Comment by markmhx** [comment]
This developer appears to have trouble integrating post conditions as well: https://github.com/stacksgov/Stacks-Grants/issues/172#issuecomment-929360627

**Comment by markmhx** [comment]
Also, is this older issue related / a duplicate? https://github.com/blockstack/docs/issues/1202

**Comment by agraebe** [comment]
yes, it is related. just wasn't in the Hiro docs issue list. If we focus on Hiro docs, this is mostyl about _how_ to use our tools to leverage post conditions

**Comment by LakshmiLavanyaKasturi** [comment]
Here is the documentation: https://docs.hiro.so/stacks.js/getting-started#post-conditions.
