### ISSUE TITLE
Add example for each API endpoint

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/docs#101]
Note from @bowtieddeployer:

> for every api have a specific example explained 

> - this is the contract
> - this way it is called specifically on it

> this gets a better learning curve for using a given api for the first time, after using it once it is enough the theory because you already know an example where you applied it

**Comment by LakshmiLavanyaKasturi** [comment]
https://github.com/hirosystems/stacks-blockchain-api/pull/1247

**Comment by LakshmiLavanyaKasturi** [comment]
Created a new issue to add examples for the remaining APIs'. Hence marking this issue as done.
