### ISSUE TITLE
Add a step-by-step guide on "clarinet integrate"

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/docs#102]
From @bowtieddeployer:

> it'd be useful to have the commands for deploying a smart contract after the blockchain is running with `clarinet integrate`

**Comment by sabbyanandan** [comment]
Many other new features are published in the blog: https://www.hiro.so/blog/meet-4-new-features-in-clarinet, which can also be listed in the Docs.

**Comment by LakshmiLavanyaKasturi** [comment]
Feature guides for Clarinet Integrate are added to the docs. -https://docs.hiro.so/clarinet/feature-guides/clarinet-integrate. Hence marking this issue as Complete.
