### ISSUE TITLE
How to enable FT metadata processing on DevNet

### ISSUE THREAD

**Issue by agraebe** [hirosystems/docs#11]
surfaced in this conversation: https://github.com/blockstack/stacks-wallet-web/issues/1700#issuecomment-927125802

Looks like a custom Docker image needs to be specific in the toml file

**Comment by fiftyeightandeight** [comment]
Hi @agraebe , I assume we are still trying to figure out how to configure Config.toml to enable FT metadata processing?

**Comment by agraebe** [comment]
It looks like @philipdesmedt figured it out with Ludo's help. I haven't seen the instructions myself (yet)

**Comment by philipdesmedt** [comment]
I haven't figured this out yet :)

Ludo told me to try a custom Docker image but I haven't had time (not do I want to spend it on this right now in all honesty)... I just assume the post conditions will work on testnet/mainnet if they work locally without the decimals parsing.

**Comment by agraebe** [comment]
Ah, I see. @lgalabru what were your suggestions to enable FT metadata processing on DevNet?

**Comment by lgalabru** [comment]
I ll test and update the default image being pulled by devnet

**Comment by sabbyanandan** [comment]
Addressed in https://github.com/hirosystems/clarinet/pull/130.
