### ISSUE TITLE
Support of SIP-013 Semi-Fungible Token standard

### ISSUE THREAD

**Issue by fiftyeightandeight** [hirosystems/docs#110]
[SIP-013 Semi-Fungible Token standard](https://github.com/stacksgov/sips/pull/42) is now in the **Accepted** status, and there are contracts already using the standard on mainnet.

Examples:

**semi-fungible trait**: https://explorer.stacks.co/txid/0x74db763fbaa66da3368e642ddac48dc5ac81f3c6e5a9b1aaf358c5745608fdde?chain=mainnet
**yield-alex-v1**: https://explorer.stacks.co/txid/0x960dda517da8f9a71d8bf7736fc09bddfa5a7035f148387cd737eab73dcc62a6?chain=mainnet
**key-alex-autoalex-v1**: https://explorer.stacks.co/txid/0x81dfeb1dc081781e8fe6859ebfc6c4ce68b61b2d329b294f44649115dab3ac59?chain=mainnet
**ytp-alex-v1**: https://explorer.stacks.co/txid/0xc0283d14f4541b9c2844839fda971547c7318ec924115ce44be9109bb85bb9a7?chain=mainnet

Based on the above, it will be great to see Hiro wallet supporting SIP-013 standard.

**Comment by 314159265359879** [comment]
Is the lack of support the reason decimal marks are not currently shown correctly in the wallet? I have made an issue here: https://github.com/hirosystems/stacks-wallet-web/issues/2506

I was wondering what else requires attention for the wallet to support these tokens. I would love to see this too, I expect this standard will get a lot more uses in the future.

**Comment by Hero-Gamer** [comment]
yes please

**Comment by 314159265359879** [comment]
rafael from Hiro says the Stacks API does not yet support semi-fungible token (SFT) metadata. 

For fungible tokens (FT) the call would look like 
`https://stacks-node-api.mainnet.stacks.co/extended/v1/tokens/SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9.key-alex-autoalex-v1/ft/metadata`

But that doesn't work for semi-fungible... after API support is added the call may look something like this?:
`https://stacks-node-api.mainnet.stacks.co/extended/v1/tokens/SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9.key-alex-autoalex-v1/sft/metadata`

After, API support is added, Hiro Wallet can add support to show correct decimal point for SFT. 

Any other wishes?
