### ISSUE TITLE
Reuse remote MD files instead of duplicating

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/docs#126]
The goal is to import the README from https://github.com/hirosystems/stacks-hyperchains/blob/master/README.md#getting-started

**Comment by sabbyanandan** [comment]
Relates to https://github.com/hirosystems/stacks-hyperchains/issues/139.

**Comment by janniks** [comment]
<img width="1624" alt="Screen Shot 2022-07-28 at 14 51 46" src="https://user-images.githubusercontent.com/6362150/181615502-8226debe-ac57-4b90-997f-071b8b3b4109.png">
Just a bad mockup based on our docs homepage, but I feel like the `Get Started` is getting very cluttered. I would love to see a high-level split based on Product/Type (eg Node/API, Stacks.js, Clarity, Gaia, etc.) and then have each things get its own `Getting Started` section.  —  _Just thinking out loud..._

**Comment by LakshmiLavanyaKasturi** [comment]
First draft of the readme file is on Notion: https://www.notion.so/hiropbc/Subnets-Readme-md-1fa867fbdeec47b4bde9f93943f09901

**Comment by LakshmiLavanyaKasturi** [comment]
The possible approaches to solve the issue is noted in the Notion page: https://www.notion.so/hiropbc/Creating-sub-module-and-link-to-refer-files-from-a-different-Git-repo-d2a888dbc9a34bc695bb08bf21218c12

**Comment by sabbyanandan** [comment]
If we have to copy over content either from the source repo to docs or vice-versa through `submodules` and symlink'ing, that I am not sure would be ideal for us. Both the approaches defined in the doc rely on this model, so we may want to drill into the pros & cons more carefully. 

FWIW, I ran into a few interesting threads on this subject with Docusaurus. 

1- A very insightful discussion at https://github.com/facebook/docusaurus/discussions/6086 — and specifically, the `docusaurus-plugin-remote-content` approach works without much lift locally on my fork. I can get the remote repo MD file (eg: https://github.com/sabbyanandan/error/blob/master/docs/test.md) in a directory of choice within the Docs repo at build time and use it at will afterward. And this copying over will work on every upstream change automatically. Perhaps some basic delta/file-diffing in action to trigger the copy event. In the same discussion, there is also the approach of having multiple docusaurus sites, one for each product repo, and then centrally assembling them with redirects etc. It sounds complex, but worth reading the specifics. 

2- The use of `@docusaurus/plugin-content-docs` plugin discussed at: https://stackoverflow.com/questions/60783595/is-there-a-way-to-have-two-docs-in-docusaurus-2/68162605#68162605 is worth reading. Unfortunately, this plugin's `path` property is relative to the repo, so it doesn't work with remote repos. But with a combination of `docusaurus-plugin-remote-content` and this plugin, we could create a good structure with different "docs folder" for each product, so the product-specific MD files we import are separated cleanly.

I am no expert with Docusaurus, so please take all this with a grain of salt. If we look more, there are probably other approaches, too. Ultimately, we want to ensure the approach we select sets up for easy importing and reuse of existing MD files (instead of duplicating), and less maintenance overhead.

WDYT, @LakshmiLavanyaKasturi?

Also, @trichards-hiro, you may have a more profound understanding of these plugins or may even have other ideas. It'd be great to hear your thoughts.

**Comment by LakshmiLavanyaKasturi** [comment]
@sabbyanandan  symlinking would mean there is no copy over. The code resides in a single location and the other is just a copy of the original. Changing one automagically changes the other and there is no copy over part. 

I have not worked with docusaurus before and this is my first time working with it. I need to go over the documentation in a more detailed fashion to understand this better. 

@trichards-hiro  do you have any suggestions over what would be relevant or easy to implement for our use case?

**Comment by LakshmiLavanyaKasturi** [comment]
https://github.com/rdilweb/docusaurus-plugin-remote-content/discussions/44

**Comment by LakshmiLavanyaKasturi** [comment]
All the possible approaches are noted on the Notion page: https://www.notion.so/hiropbc/Docusaurus-plugins-to-get-remote-content-to-docs-repo-d2a888dbc9a34bc695bb08bf21218c12

Developers can weigh in and suggest the approach that they want to go with.

**Comment by LakshmiLavanyaKasturi** [comment]
Updated developer feedback from Clarinet, Stacks.js, and API teams on [this](https://www.notion.so/hiropbc/Docusaurus-plugins-to-get-remote-content-to-docs-repo-d2a888dbc9a34bc695bb08bf21218c12) Notion page.

**Comment by LakshmiLavanyaKasturi** [comment]
This is complete
