### ISSUE TITLE
Add document for `isStacksWalletInstalled()`

### ISSUE THREAD

**Issue by yknl** [hirosystems/docs#129]
The Stacks connect function `isStacksWalletInstalled()` is not documented and developers do not know you can use this to check if a Stacks wallet is installed. Many developers have asked us (Xverse) how they can know if a Stacks wallet is installed. 

Function is here: https://github.com/hirosystems/connect/blob/main/packages/connect/src/utils.ts#L5

**Comment by sabbyanandan** [comment]
Thank you for reporting this, @yknl. Appreciate it.

**Comment by LakshmiLavanyaKasturi** [comment]
Feature guides for Clarinet Integrate are added to the docs. -https://docs.hiro.so/clarinet/feature-guides/clarinet-integrate. Hence marking this issue as Complete.

**Comment by LakshmiLavanyaKasturi** [comment]
@janniks I think the link is mentioned in https://stacks.js.org/. Can you please confirm if the link still works and if the method "isStacksWalletInstalled()" is documented? Thanks!

**Comment by janniks** [comment]
https://connect.stacks.js.org/functions/_stacks_connect.isStacksWalletInstalled.html This is the auto-generated docs, but we should add a tutorial style section for Connect in hiro.docs.so as well.

**Comment by LakshmiLavanyaKasturi** [comment]
Fixed in PR: https://github.com/hirosystems/docs/pull/254
