### ISSUE TITLE
New doc: Add a Guide for clarinet testing. Ensure all the keywords, functions are explained with their purpose.

### ISSUE THREAD

**Issue by BowTiedDeployer** [hirosystems/docs#133]
The main resource that provide information in this direction is https://deno.land/x/clarinet@v0.31.1/index.ts?code.

A guide that would provide directions for implementing tests for different use cases would be great. That would ease the testing development for all devs especially newcomers.

eg. how to take from a map response a given key and compare it with expected uint value 
```js
block.receipts[0].result.expectOk().expectSome().expectTuple()["head-id"].expectUint(1);
```

Reference docs: #226 #209. 

@mefrem can help with more info.

**Comment by LakshmiLavanyaKasturi** [comment]
Looks like this is being addressed in the PR: #226.

**Comment by LakshmiLavanyaKasturi** [comment]
@mefrem Per our discussion, we will be coming up with a new document to include a detailed explanation of all the keywords used to implement tests. I am moving this to our Ice box/To-do list to implement soon! Thanks, @BowTiedDeployer.

**Comment by LakshmiLavanyaKasturi** [comment]
Relates to https://github.com/hirosystems/docs/issues/209

**Comment by mefrem** [comment]
With new clarinet-sdk efforts, this might be worth a look from @hugocaillard to give comment on state of a proper guide or documentation to writing unit tests with Clarinet, including simnet objects and actions (mining blocks, calling methods, calling contracts, etc.).

**Comment by hugocaillard** [comment]
@mefrem Yep, https://github.com/hirosystems/docs/issues/412#issuecomment-1739830692 will take over this one
