### ISSUE TITLE
Add Developer Survey banner

### ISSUE THREAD

**Issue by eugeniadigon** [hirosystems/docs#135]
Please add a banner to the Docs homepage to help promote the Developer Survey

Design: https://www.figma.com/file/6nhAktS0TPemu9emfBkv0q/Drafts?node-id=2160%3A6283

It should link to: survey.hiro.so

@hirosystems/marketing Can you please confirm by which date you want this live?

Thanks!

**Comment by sabbyanandan** [comment]
This is now complete.
