### ISSUE TITLE
Reorganize left-nav by product

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/docs#138]
Each product-specific left-nav would include:
- [Product-name] Overview
  - Introduction
    - 2 mins product video || demo video
    - Architecture
  - Getting started
  - Feature guides
  - How-to guides
  - Troubleshooting
  - FAQ
  - Developer Resources
    - Videos
    - Blogs
    - GitHub

Goals:
- The above template would be applied for each product, so it'd be consistently presented, segmented with right content, and is easily discoverable
- Bring the wealth of YT videos/blog content closer to the docs, so we can reuse those assets and present them in one place; less discovery fatigue and context-switching for developers 
- See how we can reuse the existing but fragmented content from README, blogs, etc. (the less we duplicate in docs, the better)
- Execute on this reorganization (tactically) now and until we redo the information architecture
- See if we can templatize the left-nav structure, so we can reuse it for each product, and by changing it in 1 place, it would automatically reflect at all references [low-priority/stretch] 

Design consideration:
- Get this reorg up and running using Docusaurus until we will revisit the tooling
- Have all product-specific left-nav items collapsed by default
- Test the search functionality to ensure searching works across all the collapsed left-nav sections

**Comment by trichards-hiro** [comment]
Here is what I would propose for the navigational structure for each product in our documentation.

----------------------------------------------------------------------------

1. [Product-name] Overview

- Introduction
- Beginner Tutorials (2 mins product videos || demo videos)
- Architecture
- Concepts
- Onboarding

2. Getting started

- Prerequisites
- Requirements
- Sample End-To-End Use Case

3. Feature guides

4. How-to guides

5. Troubleshooting

- Common Issues/Workarounds

6. FAQ

7. Developer Resources

- Sample Projects
- Examples
- Videos
- Blogs
- GitHub

----------------------------------------------------------------------

This is just a preliminary idea of what our docs might look like. If we follow Stripe and other sites that we like, this left pane navigation can be a goos starting point for building our content model and navigation strategy,

**Comment by sabbyanandan** [comment]
Thanks, @trichards-hiro. I am excited for you to get this rolling! 

- You could extract the how-to guides from this spreadsheet: https://docs.google.com/spreadsheets/d/1ILpaptKepKBGHSSTUrcY-qAsZw9KdxowrTU4c49NQHk/edit#gid=0
- Product-specific FAQs and troubleshooting guides: https://drive.google.com/drive/folders/1QjWJJoE4lNMiK8TJ5CtdmwYaxpj5KecV (we need to source more)
- The examples and sample apps are already on the Docs site
- The missing feature guides you could extract from the product READMEs (example: [Clarinet](https://github.com/hirosystems/clarinet/blob/develop/README.md))

As you work through the re-org and you need help with missing content, let's capture them, and we can source the essential details with the help of the right folks in the team, which you could then polish.

**Comment by sabbyanandan** [comment]
To make this clearer, here's a snapshot of the left-nav with how we wanted to present the product-specific left-nav rollups:

<img width="1475" alt="image" src="https://user-images.githubusercontent.com/1562654/191616220-de5505d6-b3ec-42a0-bda8-93d6f0df065f.png">

All this boils down to 2 objectives:

(1) Add the four top-level product categories on the left-nav: Explorer, Clarinet, Stacks blockchain API, and Stacks.js

(2) Each product have the following sub-nav as line-items:
- Introduction
  - 2 mins product video || demo video
  - Architecture
- Getting started
- Feature guides
- How-to guides
- Troubleshooting
- FAQ
- Developer Resources
  - Videos
  - Blogs
  - GitHub

**Comment by sabbyanandan** [comment]
Addressed in https://github.com/hirosystems/docs/commit/2ac6d6e8c01c18f6b11a197e70467b519bf9e0f5. 💥
