### ISSUE TITLE
Typo in stacks.js starter templates 

### ISSUE THREAD

**Issue by elenananana** [hirosystems/docs#142]
> The form below le**t's** you generate a new project with a few clicks.

**Comment by sabbyanandan** [comment]
Hi, @elenananana. This is what I see on the site:

> The fastest way to start a new JavaScript project using Stacks.js — web3 here we come! The form below let's you generate a new project with a few clicks. We have prepared minimal example templates for the most common frameworks. Are we missing any? [Let us know!](https://github.com/hirosystems/stacks.js-starters/issues/new) Check out all the templates in the [stacks.js-starters GitHub repository](https://github.com/hirosystems/stacks.js-starters/tree/main/templates).

It seems correctly set. What am I missing?

**Comment by janniks** [comment]
Ah right, should be “lets” — thanks
