### ISSUE TITLE
Redo navigation flow for Stacks.js

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/docs#147]
Relates to #138

**Comment by sabbyanandan** [comment]
For features-gudie, we could include the following.

I could see the various JS libraries we ship fit in that category: https://github.com/hirosystems/stacks.js#connecting-wallets

We could expand what each library does with a description. Perhaps in a table format?

Maybe also https://github.com/hirosystems/stacks.js#importing--polyfills fits as a feature, which we can describe.

We can also talk about https://docs.hiro.so/stacksjs-starters as a feature for bootstrapping projects quickly.

**Comment by janniks** [comment]
https://github.com/hirosystems/stacks.js#importing--polyfills is going to change (be removed soon), so doesn't need to be documented further...

**Comment by sabbyanandan** [comment]
Addressed in https://github.com/hirosystems/docs/commit/2ac6d6e8c01c18f6b11a197e70467b519bf9e0f5.
