### ISSUE TITLE
Clarinet - README polish

### ISSUE THREAD

**Issue by LakshmiLavanyaKasturi** [hirosystems/docs#180]
With the vscode extension v1 release, we need to rework the README. It will appear here on github, on the marketplace (as well as within vscode).
Here’s a screenshot of the current version, we already reworked the name, description and tags about 4 month ago (here),

 but the readme could really be improved as well.
We could highlight the fact that it runs in the browser, remove the paragraph that says “This extension relies on a local installation of Clarinet [...]” (except for the DAP for now).
I think it could have two part,
showcase the feature of the extension and why it’s so great :relieved:
technical part (contribute, run it locally, architecture,  etc)

<img width="1216" alt="Screenshot 2022-10-03 at 18 09 23" src="https://user-images.githubusercontent.com/55154433/193633350-b935f665-0e25-490e-bca3-91764f9320c3.png">

For any further questions: Reach out to Hugo.

**Comment by sabbyanandan** [comment]
This is now complete.

**Comment by lgalabru** [comment]
Thank you Sabby and Thomas! I renamed this issue to avoid confusion - we revisited the VSCode Extension's page, but we still need help on re-structuring Clarinet's README.

**Comment by sabbyanandan** [comment]
Oh, missed that one, Ludo. Let's use https://github.com/hirosystems/clarinet/issues/478 to address the main README. @trichards-hiro, I will assign https://github.com/hirosystems/clarinet/issues/478 to you for continuity.
