### ISSUE TITLE
Stacks Blockchain API: Update "Microblocks" feature guide to use latest content and examples

### ISSUE THREAD

**Issue by trichards-hiro** [hirosystems/docs#182]
Our current examples for the Microblocks section of the Stacks Blockchain API docs should be updated with "better" examples.

This issue is to improve the [Microblocks document](https://docs.hiro.so/stacks-blockchain-api/feature-guides/microblocks) in the Stacks Blockchain API. 

Edit the page in the Stacks blockchain API repo: https://github.com/hirosystems/stacks-blockchain-api/blob/develop/content/feature-guides/microblocks.md
Next, redeploy any prod build on docs to pull the changes to docs repo.

@zone117x can provide more information.

**Comment by mefrem** [comment]
Microblocks are deprecated with Nakamoto, unclear the priority or need for this issue.
