### ISSUE TITLE
Stacks Blockchain API : Update "Error Handling" page to use the latest content and examples

### ISSUE THREAD

**Issue by trichards-hiro** [hirosystems/docs#183]
This issue is to update the https://docs.hiro.so/stacks-blockchain-api/how-to-guides/how-to-handle-errors document with the latest content and examples. 

@zone117x can help with more information

**The below comment was from Thomas's conversation with Matt.**
comment from Matthew:

"This is not exhaustive (neither are the linked resources) since they come from outdated OpenAPI schema from when the Hiro API used to be the only project that attempted to document and create schemas for the Blockchain RPC interface.

The stacks-blockchain repo is now the canonical source for these specs, and the Hiro Stacks API documentation for these will likely be removed. Potentially replaced with a loosely-coupled reference to the Blockchain RPC repo docs if the tooling permits."

**Comment by ryanwaits** [comment]
https://github.com/hirosystems/stacks-blockchain-api/pull/1744
