### ISSUE TITLE
Stacks Blockchain API: Create distinct sets of documentation for both the Stacks Blockchain's RPC interface and the Stacks Blockchain API.

### ISSUE THREAD

**Issue by trichards-hiro** [hirosystems/docs#184]
Summary: 

This issue is to separate documentation for Stacks Blockchain's RPC interface and the Stacks Blockchain API. Currently, we have all the documentation located [here](https://docs.hiro.so/stacks-blockchain-api/overview).

@zone117x can help with more info.

** The below section is a detailed version of @zone117x's suggestions **
Several commenters mentioned that there needs to be a clear distinction made in our docs between Hiro API and RPC endpoints.

Here are the specific comments:

"This may be nit-picky, but I don't feel super comfortable leaning into this kind of "product description".

Often folks will colloquially use the term "API" to refer to one or both of the Hiro Stacks API and/or the Blockchain RPC interface. After all, API is a vague term that technically does describe both. However, the Hiro Stacks API is a distinctly different product and service than the Blockchain RPC endpoints.

Even from a documentation perspective, both have significantly different implementations, availability, and maintenance both internally and publicly facing.

Docs that seamlessly intertwine these two products together seem odd -- like if Microsoft Azure seamless merged Docker documentation with their Docker-adjacent service offerings, or like if Cloudflare merged the IPFS protocol docs with their IPFS gateway related offering docs, etc..

I think it's okay and probably good that Hiro docs cover protocol/blockchain-specific features like the RPC endpoints, but intermingling them together in a way that makes the Hiro Stacks API and RPC endpoint seem like the same product has historically been a consistent pain point, and these docs appear to continue down this route.

Digitalocean docs are a great example of where they document and create tutorials for many popular products, but never in a way where the reader leaves thinking something like "digitalocean services = ubuntu&nginx", and then reaching out to digitalocean when they have ubuntu&nginx questions/issues.

cc @CharlieC3 for possibly more insight into this situation. IIRC the new miroservices and new endpoint structures will also have some impact here."

and:

"+1 For establishing a larger separation between the two service APIs. Despite having similar naming, I feel we should treat them like two different products. There is some overlap, but the intended use behind them is vastly different. IMO the Stacks Blockchain's RPC interface is better for directly interacting with the Stacks blockchain, quick debugging, and high-level status observations--something a developer might use when locally running a node. Whereas the Stacks Blockchain API is a more comprehensive and data-rich solution is almost every aspect. It cannot submit TXs to the blockchain, but is better for long-standing environments and people that want deeper introspection into the blockchain.

I would imagine people get these two APIs confused and mixed up frequently. Instead of saying the API is comprised of two parts, it might be better to clarify that the Stacks Blockchain API is not the Stacks Blockchain's RPC interface, and if you're looking for documentation on the Stacks Blockchain's RPC interface to go here maybe."

**Comment by ryanwaits** [comment]
hey @sabbyanandan, revisiting some of our older issues to ensure nothing is falling through the cracks - given where docs are at now, do you think this is still an active concern?

**Comment by sabbyanandan** [comment]
I would vote for closing it. 👋🏽
