### ISSUE TITLE
Stacks Blockchain API / Clarinet - Find the best place for the "Using Clarity Values" doc inside Stacks Blockchain API and update the doc with latest content and examples

### ISSUE THREAD

**Issue by trichards-hiro** [hirosystems/docs#185]
Summary:

- [Use clarity values](https://docs.hiro.so/stacks-blockchain-api/feature-guides/use-clarity-values) page inside of Stacks blockchain API can be removed and added to the Clarinet repo docs. 

- [Use clarity values](https://docs.hiro.so/stacks-blockchain-api/feature-guides/use-clarity-values) doc can be updated with the latest content and examples.

** The below section is a detailed version of @zone117x's suggestions **
There were several comments made about this page and how we should properly message this content. Here are the comments:

"Similar to the last comment about the RPC endpoints vs the Hiro Stacks API -- this page has essentially no relation to the Hiro Stacks API.

Incidentally the @stacks/blockchain-api-client package includes types/functions that interact with the Stacks Blockchain RPC endpoints -- but that is generally only a vestigial artifact from the Blockstack days where the API was the only codebase that had OpenAPI documentation for those endpoints. That is no longer the case --the Stacks Blockchain repo maintains its own OpenAPI schema/docs, and the leftovers inside the Hiro Stacks API are outdated and are planned for removal.

From a product perspective, once the Blockchain RPC spec is removed from the API repo, they will automatically also be removed from the @stacks/blockchain-api-client Hiro library."

and:

"Following up with a potential alternative: Hiro maintains the @stacks/* / stacks.js packages which do intentionally interact the the RPC endpoints. Perhaps there are stacks.js lib/functions to replace these?

cc @janniks

Even if stacks.js does not have an explicit function to help invoke something like the POST /v2/contracts/call-read/... functionality described here, it could still be used to manually construct such calls."

and:

"RE RPC:
You only mean the /v2 endpoints (proxied RPC HTTP API from https://docs.hiro.so/get-started/stacks-blockchain-api), right? Should any non-"extended" API calls be excluded from blockchain-api-client in the future? (Or be treated as if they were excluded)

I like the DigitalOcean blog post approach. We can make it more clear what the API is adding and what it does have control over.
But I do like the client having access to all endpoints (proxied or otherwise), rather than needing two libs or something. And (at least currently) the API proxies those requests (I'm not sure what the exact devops changes entail).

I do like the concept of having one thing (even if it's a docker-compose with multiple "children"), which one can start and have all the fancy features (node++). This is likely what companies might want to self-host (e.g. for professional products), compared to individuals maybe only needing a private node (e.g. to connect to their wallet).
If that thing would be the API and node together (treating the two as siblings rather than parent+child / proxy+child); that would be fine as well. I guess it's just a naming problem... But I might be missing something here

If most of this specific article purpose lies in the JS-world, we can move it over to the Stacks.js pages and reference from the API pages. Also, we can rework it to showcase a Stacks.js method and maybe document the used endpoints for available Stacks.js methods."

and:

"It's a likely outcome. The stacks-blockchain repo is the canonical source for OpenAPI & schemas for the RPC endpoints. The historical/legacy spec in the Stacks API is already outdated and incorrect. As mentioned in another comment, we may introduce some kind of hyperlink reference to the Blockchain RPC spec (if tooling permits), otherwise the best course of action is to remove the dead spec and direct folks to the canonical & up-to-date source -- the Blockchain repo. This has been planned and in discussion for quite some time.

Similar to how Cloudflare hosts an IPFS gateway -- Hiro is a 3rd party that hosts a Blockchain RPC service, but with minimal control over the implementation, changes, bugs, etc.

It sounds reasonable to me if we ended up with a js library created for the Blockchain RPC endpoints, and had separate docs for those -- similar to how many 3rd parties offer tools for AWS S3. It could have plenty of references/pointers to the Hiro Stacks API and vice versa at a documentation level.

But to do otherwise really seems strange. Like for example if cloudflare offered a @cloudflare/client library which wholesale copy&pasted outdated code from a canonical @ipfs/client package, with accompanying documentation that did not distinguish between the two. That is the situation we are currently in."

**Comment by hugocaillard** [comment]
> "this page has essentially no relation to the Hiro Stacks API"

Should it be moved to the Stacks.js section?
Happy to help providing some more relevant / generic code examples regarding how to manipulate clarity values with these methods if that's needed 👍

**Comment by ryanwaits** [comment]
https://github.com/hirosystems/docs/pull/558
