### ISSUE TITLE
New document: Add Hiro Glossary of terms

### ISSUE THREAD

**Issue by trichards-hiro** [hirosystems/docs#192]
Add a Glossary of terms to the Hiro docs, possibly under the Other section. 

![image](https://github.com/hirosystems/docs/assets/55154433/6c5d8ccf-c782-45e2-8227-792ee4aa20e0)

References: https://www.notion.so/hiropbc/Glossary-5e0a1122fd03407ea7502c1b8f41a070?pvs=4

Inspiration: https://docs.stacks.co/docs/glossary/
https://developers.google.com/machine-learning/glossary

@elenananana, might be able to help with more info.

**Comment by diwakergupta** [comment]
Do we still need this? Most of the terms in the linked Notion doc don't seem very relevant to technical documentation. I'd advocating for closing this out for now, wdyt @elenananana @saralab
