### ISSUE TITLE
Updated Feature Guides for Clarinet V2

### ISSUE THREAD

**Issue by elenananana** [hirosystems/docs#196]
Hi Docs team!

We are gearing up to formally announce Clarinet V1.

The release is already out but we are planning supporting content such as videos and a blog to highlight some key features, namely Clarinet Integrate, Chainhooks and Deployment Plans. Is it possible to include feature guides for these features in docs.hiro.so? 

**Clarinet Integrate** - brief description "this is clarinet integrate. you can use this feature to do x,y,z." 

- [YT overview ](https://www.youtube.com/watch?v=or01j0a9MUo&list=PL5Ujm489LoJaAz9kUJm8lYUWdGJ2AnQTb&index=11)- shows off integration, I believe this is an overview of clarinet integrate
- [YT overview](https://www.youtube.com/watch?v=4V0hcuOq47I&list=PL5Ujm489LoJaAz9kUJm8lYUWdGJ2AnQTb&index=13), this is more advanced, but this information might be helpful
- there is some description of Clarinet Integrate in the Clarinet main README and hiro docs already (run a local integration and deploy with subnets sections). A few terms that need to be defined - devnet, unit test, etc.

**Chainhooks** - feature guide could focus on "these are chainooks. you can use this feature to do x,y,z." You can find this language [here](https://www.hiro.so/blog/meet-4-new-features-in-clarinet).
[cBTC example](https://github.com/hirosystems/clarinet/tree/develop/components/clarinet-cli/examples/cbtc) shows how to use this feature
These are Github PRs that describe chainhooks: [#402](https://github.com/hirosystems/clarinet/pull/402), [#564](https://github.com/hirosystems/clarinet/pull/564), [#577](https://github.com/hirosystems/clarinet/issues/577)

**Deployment Plans** -
Described in this [video](https://www.youtube.com/watch?v=ciHxOGBBS18), around the 8 minute mark
"primitives that help teams build together. create standardized protocol for deploying smart contracts on any network based on stacks or bitcoin (devnet, testnet, mainnet)....domain specific language that can be committed, audited, tested"
Briefly described in the Clarinet README in the external deployer section.

**Comment by elenananana** [comment]
@LakshmiLavanyaKasturi - do you have an estimate for this?

**Comment by LakshmiLavanyaKasturi** [comment]
@elenananana While I am focused on getting the plugin out for all the products, I requested Thomas to take this content. I am happy that he accepted and took over it. 
Sorry for any delay caused in this regard. We hope to get these features on Docs asap. Thanks! 

@trichards-hiro Thank you!
@sabbyanandan FYI

**Comment by LakshmiLavanyaKasturi** [comment]
Changes are added to the PR: https://github.com/hirosystems/docs/pull/219

**Comment by LakshmiLavanyaKasturi** [comment]
Update the description to use it for V2.
