### ISSUE TITLE
Update README for Subnets re: Licenses

### ISSUE THREAD

**Issue by saralab** [hirosystems/docs#199]
Can we include the following details to the Subnets Readme which most likely were lost with the recent changes  
- License Information 
- Instructions to build Subnets
- Instructions to run tests

**Comment by saralab** [comment]
@ezinneokpo : Help with determining the right license here please. We had GPL V3 in the past that we copied over from Stacks and that needs to be updated.

**Comment by LakshmiLavanyaKasturi** [comment]
According to Greg, it is appropriate to include the following sections in the _Getting started_ section of Subnets-readme.

1. License information:
2. Instructions to build subnets:
    1. Instructions to build Subnets
        - Clarinet -  link to NFT use case
        - If a user wants to do local testing - add a link to [localtesting.md](http://localtesting.md/)
        - Testnet → add link to [Deploying.md](http://deploying.md/)
3. Instructions to run tests
    a. `cargo test`
    
    This command shows the results of the pass and fails list.
    
    b. `testnet/stacks-node$ cargo test`
    
    `Gregs-MacBook-Pro:stacks-subnets greg$ cd testnet/stacks-node/`
    `Gregs-MacBook-Pro:stacks-node greg$ cargo test`
    
    c. `testnet/stacks-node$ cargo test -- --ignored --num-threads=1` (Optional)

**Comment by LakshmiLavanyaKasturi** [comment]
@ezinneokpo: Any update on the license?

**Comment by LakshmiLavanyaKasturi** [comment]
> @ezinneokpo: Any update on the license?

Adding Ezinne update to this PR:

License will be GPLv3. Need to check in on the copyrights.

**Comment by LakshmiLavanyaKasturi** [comment]
PR: https://github.com/hirosystems/stacks-subnets/pull/170 is ready with the updates for README.md. License info is pending to be added.

**Comment by LakshmiLavanyaKasturi** [comment]
@ezinneokpo : Any updates on the License info?
