### ISSUE TITLE
Add product guide for Subnets

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/docs#200]

**Comment by LakshmiLavanyaKasturi** [comment]
https://github.com/hirosystems/docs/pull/205

**Comment by LakshmiLavanyaKasturi** [comment]
@trichards-hiro: Please link your Subnets PR to this task. Thanks!

**Comment by trichards-hiro** [comment]
This issue relates to PR #224 (https://github.com/hirosystems/stacks-subnets/pull/224)

**Comment by LakshmiLavanyaKasturi** [comment]
PR : https://github.com/hirosystems/docs/pull/338

**Comment by sabbyanandan** [comment]
This is complete.
