### ISSUE TITLE
Add latest version to archiver files

### ISSUE THREAD

**Issue by igorsyl** [hirosystems/docs#202]
This link seems broken:

```
% wget https://storage.googleapis.com/hirosystems-archive/mainnet-blockchain-2.05.0.2.2-latest.tar.gz
--2022-10-19 08:49:58--  https://storage.googleapis.com/hirosystems-archive/mainnet-blockchain-2.05.0.2.2-latest.tar.gz
Resolving storage.googleapis.com (storage.googleapis.com)... 142.251.32.16, 172.217.4.48, 142.250.190.16, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.251.32.16|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-10-19 08:49:58 ERROR 404: Not Found.
```

Also, it would be helpful to add a symlink to the current version:
```
https://storage.googleapis.com/hirosystems-archive/mainnet-blockchain-current-latest.tar.gz
```

**Comment by sabbyanandan** [comment]
Yikes! Thanks for flagging this, @igorsyl. A symlink idea is clever, and we could avoid maintaining the release versions on this page.

@deantchi: When you get a chance, could you take a stab this, please?

**Comment by sabbyanandan** [comment]
@deantchi: Thanks! Any thoughts on the symlink that always points to the latest release? With that, we manage the mapping behind the scenes and can avoid maintaining this page on every release.

**Comment by deantchi** [comment]
> This link is broken too:

@igorsyl `2.05.0.2.2` is no longer available.  `2.05.0.3.0` should be used

**Comment by deantchi** [comment]
> @deantchi: Thanks! Any thoughts on the symlink that always points to the latest release? With that, we manage the mapping behind the scenes and can avoid maintaining this page on every release.

I feel having the `datestamp` and `data version` in the filename is necessary to determine what version of the application is needed to use the archive files.

**Comment by sabbyanandan** [comment]
@igorsyl: The caveat to these files we host is that we don't have any data validation or use this file internally in any of our products, so the version we publish is with the assumption that developers can grab the pinned version and if there are issues with it, they will report, and we _will_ address them. Apart from ensuring the URL is hosted and served reliably, we cannot put the dataset to use, so given that background, having a pinned version can help narrow the blast radius. And that change is included in https://github.com/hirosystems/docs/commit/fab750c994a97b26c9ae19b729cad0de67e65ac6.

If you run into a situation where you need more than the fixed version, please reopen, and we will discuss the approach internally.
