### ISSUE TITLE
Clarinet: [vs code ext] VS Code Web Extension

### ISSUE THREAD

**Issue by elenananana** [hirosystems/docs#206]
The latest version of Clarity for VS Code now runs in the browser, allowing Stacks developers to write and deploy code without a single installation. I believe it could be helpful to include a brief description of the web extension under getting started. I think that’s all that’s needed for now.

The desired goal is to allow beginners to start coding in clarity in a matter of seconds or even experienced developer to quickly prototype without setting up an env.

- VScode is mentioned in Clarinet introduction in the blog [[here](https://docs.hiro.so/clarinet/introduction)]

- Blog post announcing the update is [[here](https://www.hiro.so/blog/write-clarity-smart-contracts-with-zero-installations-how-we-built-an-in-browser-language-server-using-wasm)]

Document to update: https://github.com/hirosystems/clarinet/blob/develop/docs/getting-started.md

@Hugo can help with any further questions.

**Comment by LakshmiLavanyaKasturi** [comment]
This issue is to document the VS code web extension. Find more details in the description.

**Comment by hugo** [comment]
> @hugo can help with any further questions.

I doubt it.
