### ISSUE TITLE
bug - api -Transactions typo

### ISSUE THREAD

**Issue by unclemantis** [hirosystems/docs#207]
![Screenshot_20221029_082009](https://user-images.githubusercontent.com/718701/198831371-9788174e-8a7e-4218-acd9-4597acb2aa5c.jpg)

**Comment by sabbyanandan** [comment]
@unclemantis: Thank you for pointing this out! The description needs an update in the `openapi.yaml` at https://github.com/hirosystems/stacks-blockchain-api/blob/299d45bc4d5259c9f1ebd6c05e435619bee7f92b/docs/openapi.yaml#L2152. 

@LakshmiLavanyaKasturi: A quick fix whenever it is convenient for you.

**Comment by LakshmiLavanyaKasturi** [comment]
@unclemantis Thanks for the find. We got a fix for it. https://github.com/hirosystems/stacks-blockchain-api/pull/1415

**Comment by LakshmiLavanyaKasturi** [comment]
Closing this issue as the PR: https://github.com/hirosystems/stacks-blockchain-api/pull/1415 is merged.
