### ISSUE TITLE
Implement add-ons to improve developer engagement

### ISSUE THREAD

**Issue by LakshmiLavanyaKasturi** [hirosystems/docs#211]
Big thinking: site arch and UIUX. 

API Try-it experience
- [ ] Come up with Redoc tool or any other tool that can integrate with Docusaurus for a try-it experience.
- [ ] UI/UX design on how the API Try-it experience would look like.
- [ ] Design wireframes for high-level docs site vision.
- [ ] Get the wireframe flow from the Hiro docs landing page to the product-specific documentation pages.
- [ ] Check if docusaurus supports multi tiles on the documentation page. Eg: Top level tile would have How-to-articles and the lower level would have how-to-article-1, how-to-article-2 etc. 
Eg: https://developers.facebook.com/support/

Vote-up/down button. (Thumbs up/down) 

- [ ] Placement of the button. 
- [ ] Decide the text.
- [ ] Thumbs down shows up a text box to enter a reason for thumbs down.
- [ ] Work with UI/UX team to come up with the design for including this feature.
- [ ] brainstorm if the following tools would be sufficient. amplitude, hotjar, Google analytics

Product Changelog

- [ ] Work with Marketing (Elena, Max, Brian) to determine what content will be included in the Product Changelog
- [ ] Decide where to place the link to the Product Changelog. Should it be added to the horizontal tabs at the top of the page? How about in the left navigation pane? Botton of the page?
- [ ] Create Changelog Slack Channel and work with Elena and Max to create Slackbot to ping PMs and Engineering Managers weekly to add any updates.
- [ ] Changelog responsibilities will alternate between Lavanya and Thomas on a monthly basis

**Comment by LakshmiLavanyaKasturi** [comment]
@trichards-hiro Can you add change log notes to this user story?

**Comment by sabbyanandan** [comment]
I bumped into a conversation of how the [React's website](https://reactnative.dev/docs/getting-started) includes a voting component, and how they implemented it in Docusaurus. While digging, I ran into this https://github.com/facebook/react-native-website/pull/3371, that supposedly adds the vote component, which can be used as a reference when implementing this in our Docs.

**Comment by LakshmiLavanyaKasturi** [comment]
The design draft for the thumbs-up and down feature is documented [here. ](https://hirosystemspbc-my.sharepoint.com/:p:/g/personal/lavanya_hiro_so/EY9-Trv3K2pCt75Wl_1xhDEBPz64U9w1HCKwgOyeTgxs2w?e=tBcHkN).
