### ISSUE TITLE
New Feature Guide for Explorer Sandbox

### ISSUE THREAD

**Issue by elenananana** [hirosystems/docs#213]
Once this PR is merged, we should update the docs to include a more detailed feature guide for the sandbox and what developers can do with it. 

https://github.com/hirosystems/explorer/pull/912

@He1DAr, can help with more info.

Feature guide template: Refer to https://www.notion.so/hiropbc/Docathon-Resources-ca2d71b19ec54ce5912a913e7422cb6f?pvs=4#270c0a2161554723b3c7e23ae01447dc

**Comment by ryanwaits** [comment]
closing.

reason: there is a larger conversation planned around explorer content inside of docs
