### ISSUE TITLE
Explorer Docs updates 

### ISSUE THREAD

**Issue by LakshmiLavanyaKasturi** [hirosystems/docs#234]
@leahjlou to include more details

**Comment by andresgalante** [comment]
Hi @LakshmiLavanyaKasturi during the past weeks we've added:

- Historical prices: so users can click on a USD price and see how much it was worth at the tx date
- Top-level stats: this is WIP not out yet
- Copy action: users can now copy the time stamp of a tx by clicking on the tooltip, it's good for tax reports
- 2.1 changes: there are 2 small changes around stacking

**Comment by LakshmiLavanyaKasturi** [comment]
@chresko : Do you have any inputs on 2.1 updates for Explorer to include in the docs?

**Comment by LakshmiLavanyaKasturi** [comment]
From the [slack- channel](https://hiropbc.slack.com/archives/C03TU42NL05/p1673628481656949) conversation, there are no doc updates required for 2.1 changes for Explorer.
Also, the other updates are minor to update in the docs.  Hence, closing this issue.
