### ISSUE TITLE
Add Docs team (Lavanya and Thomas R) to the authorized list of users to Clarinet, API, Stacks JS, and Explorer repos

### ISSUE THREAD

**Issue by LakshmiLavanyaKasturi** [hirosystems/docs#240]
Currently, the Docs team doesn't have permission to merge PRs to the product repos. With the recent remote content docs changes, the docs team will be actively updating the documentation in the product-specific repos. This issue is to add permissions to the product-specific repos.

**Comment by aravindgee** [comment]
[Tagging product team below as I do not have direct privileges for this change]

- [ ] `hirosystems/clarinet` - @lgalabru , @hugocaillard 
- [ ] `hirosystems/stacks-blockchain-api` - @rafaelcr , @zone117x 
- [ ] `hirosystems/explorer` - @andresgalante , @beguene 
- [ ] `hirosystems/stacks.js` - @zone117x , @janniks 

Hi folks, if you approve of this change, could you grant privileges to  `LakshmiLavanyaKasturi` and `trichards-hiro` to merge PRs in these repos?

**Comment by janniks** [comment]
Would it make sense to add a hiro-docs-team on github, rather than individual contributor permissions?

**Comment by tortiz-hs** [comment]
- Added Lavanya and Thomas R. to the "Docs" GH team.
- Added the "Docs" team to the desired Repos.
- Added the role of "Write" to the "Docs" team in each of these repos. 

Request has been completed!

**Comment by LakshmiLavanyaKasturi** [comment]
@tortiz-hs I still don't seem to have permission to merge PRs in the repos. I tried Clarinet and API this morning. Please verify. Thanks!

**Comment by LakshmiLavanyaKasturi** [comment]
Done
