### ISSUE TITLE
Implement an interactive Docs site focused on product discovery and education

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/docs#251]
**Why is this bet impactful to Stacks developers?**
Today, when devs go to docs.hiro.so site, they are presented with static text and entirely non-helpful details. Most users ignore the landing page and find information by clicking through the top-nav and footer-nav links and menus. The landing page could be more beneficial as it stands.

**In the absence, Stacks developers are:**
Clicking through top-nav and footer-nav links and menu choices to try and find a way to get to product-centered docs, including getting started, how-to, and feature guides. 

**We will bet against the following use-case(s):**
With a dynamic and educational-centered focus, we will reimagine the landing site as interactive and hand-holding to the developer personas. The initial cut will focus on the developer lifecycle, language, explanations, and context-specific product guidance.

**Inspiration**: 

https://learn.microsoft.com/en-us/
https://support.google.com/a/users/?hl=en#topic=9247638

@sabbyanandan can help with more info.

**Comment by ryanwaits** [comment]
@sabbyanandan closing this for now, but this is very much aligned with our current vision to turn our current docs into a "learning platform" - so we will have more specific issues coming soon getting us closer to your suggestions above
