### ISSUE TITLE
Alert users about the deprecated/EOL API changes

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/docs#260]
**Backstory:**
As a user, while browsing through the [RESTful API docs](https://docs.hiro.so/api), I would like to be notified about any upcoming deprecation and the timeline associated with it. 

**Why? A case in hand:**
In the past, we have proactively announced deprecation and removed an API via https://github.com/hirosystems/stacks-blockchain-api/pull/1329; however, the comms from Hiro weren't persistent enough or sufficiently vocal, and it had impacted developers who were relying on this API in production. Later, we reverted the change via https://github.com/hirosystems/stacks-blockchain-api/commit/68d49649779df91675c08f254504246a4d80a744 to help unblock developers. 

**Next steps:**
+ In the future, for any detrimental to significant breaking changes such as this, we will press on the Hiro's developer marketing + comms more proactively (even months beforehand), so we can be more graceful with our intent. 
+ In the [API docs](https://docs.hiro.so/api), we can add a top-level warning message with an EOL timeline for when such a change is in flight, and that warning will be persistent until the actual EOL date. 
+ In addition to the API docs, we may add the same warning message to the [API's README](https://github.com/hirosystems/stacks-blockchain-api/blob/master/readme.md). An opportunity to reuse the MD file in both README and API docs.

**Testing:**
As we release and activate the [new NFT metadata API service](https://github.com/hirosystems/token-metadata-service) in Mainnet, we can test the above-mentioned operational elements since it would require removing support for the deprecated API and other code-level cleanups. 

**Message template:**
```
The <RELATIVE-PATH-OF-API-ENDPOINT> is deprecated as of <DATE OF DEPRECATION>, and it will reach the end-of-life and go out of Hiro support on <DATE OF EOL>. 
Please prepare your upgrade and deployment plans.
```

_ps: maybe an opportunity to standardize this for all big breaking changes across **all products** in the future_

**Comment by trichards-hiro** [comment]
@sabbyanandan This is a great idea. We can potentially also roll this into the _Deprecation Policy_ doc that I will be working on later?

**Comment by ryanwaits** [comment]
@sabbyanandan this seems closely related to some more recent issues we are working on, anything here that should be carried over or can we close this?
