### ISSUE TITLE
current_cycle and next_cycle structs missing from API docs /v2/pox

### ISSUE THREAD

**Issue by edu-stx** [hirosystems/docs#262]
**Describe the bug**
The `current_cycle` and `next_cycle` props are not documented https://docs.hiro.so/api#tag/Info/operation/get_pox_info

However, they do appear in the example here,

https://github.com/stacks-network/stacks-blockchain/blob/master/docs/rpc/api/core-node/get-pox.example.json

**Comment by LakshmiLavanyaKasturi** [comment]
Thanks, @edu-stx, for your contribution. We will update the API docs.

**Comment by LakshmiLavanyaKasturi** [comment]
Fixed this issue in PR: https://github.com/hirosystems/stacks-blockchain-api/pull/1526. Thanks again!
