### ISSUE TITLE
Product change log

### ISSUE THREAD

**Issue by LakshmiLavanyaKasturi** [hirosystems/docs#266]
Product Changelog

 Work with Marketing (Elena, Max, Brian) to determine what content will be included in the Product Changelog
 Decide where to place the link to the Product Changelog. Should it be added to the horizontal tabs at the top of the page? How about in the left navigation pane? Botton of the page?
 Create Changelog Slack Channel and work with Elena and Max to create Slackbot to ping PMs and Engineering Managers weekly to add any updates.
 Changelog responsibilities will alternate between Lavanya and Thomas on a monthly basis

**Comment by LakshmiLavanyaKasturi** [comment]
Done

**Comment by sabbyanandan** [comment]
Closed via https://github.com/hirosystems/docs/commit/38703031bb254cfd40645dcc00c29aa0b14e7d11
