### ISSUE TITLE
Fix screenshots in Clarinet - How to debug contract doc

### ISSUE THREAD

**Issue by LakshmiLavanyaKasturi** [hirosystems/docs#268]
https://docs.hiro.so/clarinet/how-to-guides/how-to-debug-contract

The screenshot's font and size in this article look weird. This issue is to fix them and align with the content.

@LakshmiLavanyaKasturi can help with more info.
@Hugo can help with the content accuracy and workflow.

**Comment by hugo** [comment]
> @hugo can help with the content accuracy and workflow.

Unlikely that I can.
