### ISSUE TITLE
Reference CLI faucet docs accidentally display previous section's usage

### ISSUE THREAD

**Issue by edu-stx** [hirosystems/docs#269]
The reference docs for how to use the `faucet` command is displaying a copy of the same docs of the `encrypt_keychain` section just above it,

https://github.com/hirosystems/docs/blob/59bdb65cee4fa40a32ec18c3781f34817cf92e5b/docs/references/_commands.md?plain=1#L245-L280

**Comment by LakshmiLavanyaKasturi** [comment]
@edu-stx: Thanks for your contribution. I will update the content for the commands.

**Comment by janniks** [comment]
Note, the commands md is autogenerated from the Stacks.ja repo as well. So we should fix it there.

**Comment by edu-stx** [comment]
Noticed the cli help flag also displays the incorrect info for `faucet`. Will fixing the source of the autogeneration also take care of the cli help text?

**Comment by LakshmiLavanyaKasturi** [comment]
@janniks: Can you help update the examples in each faucet and key management command? Thanks!
