### ISSUE TITLE
Update Stacks Blockchain API documentation

### ISSUE THREAD

**Issue by pgray-hiro** [hirosystems/docs#27]
The Stacks Blockchain API documentation is lacking quite a bit of detail. Most endpoints do not have a fully realized description, and all of them lack functional examples of how to at least CURL them. The documentation is generated from the OpenAPI spec file in the `stacks-blockchain-api` repository, located [here](https://github.com/blockstack/stacks-blockchain-api/blob/master/docs/openapi.yaml).

Update the OpenAPI spec to include relevant details for every endpoint.

**Comment by agraebe** [comment]
most critically, the bonus tasks are left. the main goal of this was accomplished and we can review the bonus items during future prioritization.

thanks @saralab!
