### ISSUE TITLE
Add Hiro Platform documentation

### ISSUE THREAD

**Issue by trichards-hiro** [hirosystems/docs#275]
This issue is to create new documentation for the Hiro Platform. There are a number of different topics that need to be covered. These include:

- How to deploy a contract in 5 minutes or less.
- How to build, unit-test, debug, and deploy all from a web browser.
- How to use and leverage pre-installed developer tools and a persistent environment.

Specific docs content:

Create
- Contract examples
- Contract cloning
- Contract importing

Build
- Single-sign-on authentication
- Hosted and persistent development environment
- Pre-installed developer tools: VS Code, Clarity Extension for VS Code, Git & Clarinet

Deploy
- An intuitive UI for single and multi-contract deployments

**Comment by LakshmiLavanyaKasturi** [comment]
Done
