### ISSUE TITLE
Create an integration guide for Clarity smart contracts and frontend applications

### ISSUE THREAD

**Issue by pgray-hiro** [hirosystems/docs#28]
A critical area of app development is the integration of a smart contract with the frontend web application. Currently, our documentation provides an overview of how to develop and test Clarity smart contracts, but lacks information on how to integrate them into a frontend.

Add an integration guide to the developer documentation. A proposed outline is located in [this Google doc](https://docs.google.com/document/d/1QDmppfp5LeeTZjCqNqC2hH1-ITCc6XBgbOCxAP_GAhE/edit).

**Comment by LakshmiLavanyaKasturi** [comment]
Closing this in favour of Hiro Platform's onboarding DevEx.
