### ISSUE TITLE
Fix mempool transaction limit

### ISSUE THREAD

**Issue by obycode** [hirosystems/docs#299]
The limit here https://docs.hiro.so/api#tag/Transactions/operation/get_mempool_transaction_list needs to be updated. It says <= 200, but when I tried it, it says it must be <= 50.

**Comment by LakshmiLavanyaKasturi** [comment]
This issue is fixed in the PR: https://github.com/hirosystems/stacks-blockchain-api/pull/1552. Hence closing it.
