### ISSUE TITLE
Clean up: Tutorials are hidden and not helpful

### ISSUE THREAD

**Issue by mefrem** [hirosystems/docs#301]
This [tutorials section](https://docs.hiro.so/tutorials/clarity-nft?_gl=1*etr5jo*_ga*NTUzNDI2NDgwLjE2NjMwOTQ5MzQ.*_ga_NB2VBT0KY2*MTY3NTg3Mzk1NS4xNDcuMC4xNjc1ODczOTU1LjAuMC4w) is out of the way but contains useful, though also incomplete and outdated, information. Would like to include better tutorials and have them advertised better throughout the rest of docs.

This issue is to clean up all the documents in the Tutorial section. https://docs.hiro.so/tutorials. 
Collaboration with Engg team is required. 

@mefrem @hugocaillard, can help with more info.

**Comment by LakshmiLavanyaKasturi** [comment]
@mefrem Thanks for your suggestion. We have an icebox item to clean up and revise tutorials [here](https://github.com/hirosystems/docs/issues/78). We will certainly prioritise and get this out asap. Thanks again.

**Comment by mefrem** [comment]
Tutorials section still leaves a lot to be desired. This might be superseded by efforts to make a Product Tour tutorial with @ryanwaits. Related to this effort is the Hiro Platform code examples.

**Comment by ryanwaits** [comment]
i think we can close this with the addition of hiro hacks work
