### ISSUE TITLE
Add documentation of wire format for stacks tx on Bitcoin

### ISSUE THREAD

**Issue by friedger** [hirosystems/docs#304]
It would be helpful to understand bitcoin tx that contain data relevant for stacks, in particular how to parse tx of these types https://github.com/stacks-network/stacks-blockchain/blob/f0ed1b950ae1bafe1b23b68bced9f1eff66d7a99/src/chainstate/burn/operations/mod.rs#L312

Reference doc: https://github.com/stacksgov/sips/blob/main/sips/sip-007/sip-007-stacking-consensus.md#bitcoin-wire-formats

@obycode is the point of contact to understand more info.

**Comment by LakshmiLavanyaKasturi** [comment]
@friedger Thanks for your contribution. We are looking into this issue and will track our progress here.

**Comment by LakshmiLavanyaKasturi** [comment]
Documentation exists here : existing documentation in SIP-007: https://github.com/stacksgov/sips/blob/main/sips/sip-007/sip-007-stacking-consensus.md#bitcoin-wire-formats.
