### ISSUE TITLE
Implement new landing page

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/docs#308]
- [x] Get the UI layout done with adding tiles and images.
- [x] Integrate tile navigations.
- [x] Implement REACT and CSS components to improve the UI experience.

The plan to implement the landing page is noted here: https://www.notion.so/hiropbc/Landing-page-design-115abc8049eb4bbebbef7c1780de9bb8?pvs=4

**Comment by LakshmiLavanyaKasturi** [comment]
Relates to https://github.com/hirosystems/docs/pull/323
