### ISSUE TITLE
Fix site from timing out when navigating

### ISSUE THREAD

**Issue by markmhx** [hirosystems/docs#31]
I've tried a few times over the past few days to navigate from the index page to "Write smart contracts" but the site keeps timing out whenever I try, freezing as such:

![image](https://user-images.githubusercontent.com/28991/139681133-8e0ad9aa-e4a2-4ae7-bb01-eeb7c7f0eb5b.png)

**Comment by pgray-hiro** [comment]
@markmhx This is a Stacks docs issue - this project is for the Hiro docs. I will look into the problem on the Stacks docs site but I'm closing this issue here.
