### ISSUE TITLE
Improve Clarinet docs

### ISSUE THREAD

**Issue by friedger** [hirosystems/docs#324]
There is FAQ and troubleshoot. Both have questions.

More questions:
How to see the logs of clarinet integrate? How to see runtime errors there.

**Comment by LakshmiLavanyaKasturi** [comment]
Great point. Thanks again for helping us continuously improve our docs.

**Comment by LakshmiLavanyaKasturi** [comment]
[PR](https://github.com/hirosystems/clarinet/pull/929) is merged. Hence marking this issue as Complete.
