### ISSUE TITLE
Fix API docs on mobile IOS

### ISSUE THREAD

**Issue by LakshmiLavanyaKasturi** [hirosystems/docs#335]
Fix formatting issue with Ordinals docs on IOS mobile.

![Image](https://user-images.githubusercontent.com/55154433/230971611-75805674-a758-4950-9e64-2df29a967e59.png)

**Comment by LakshmiLavanyaKasturi** [comment]
Steps to reproduce:
1. Open the page by navigating using the left top nav and using back to menu button
2. From references choose the Ordinals API (or stackblock chain API)

![Image](https://user-images.githubusercontent.com/55154433/231653027-d4c07151-9014-4bf8-8277-a5594529945b.png)
![Image](https://user-images.githubusercontent.com/55154433/231653028-17079a72-a70f-4186-9da2-0d4bb38f99f1.png)

3. When the page is launched scroll to the top using the rubber band scroll. (Pinch the webpage down hard)

This will create the above issue.


Observations:
1. The page is a little bit better scrolling after the issue appears by navigating to the landscape mode from portrait mode
2. After the issue appears, the page is never reset until we reopen it by navigating from the references again
3. it is not simulatable from the chrome ios simulator. 

here is a screen recording of the issue simulation
https://user-images.githubusercontent.com/55154433/231654643-8923fd3c-641d-443c-9bf4-f63eaa9e6a3a.mp4

**Comment by LakshmiLavanyaKasturi** [comment]
Relates to https://github.com/Redocly/redoc/issues/2300

**Comment by sabbyanandan** [comment]
Addressed via https://github.com/hirosystems/docs/pull/347.
