### ISSUE TITLE
New documentation: Add Ordinals Explorer docs

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/docs#336]
This is a placeholder to document Ordinals Explorer, similar to our [current Explorer documentation.](https://docs.hiro.so/#). 

Documentation is to be added to the [Ordinals- explorer repo](https://github.com/hirosystems/ordinals-explorer) and pulled into the docs repo by updating the `docusaurus.config.js` and `sidebar.js files`

@LakshmiLavanyaKasturi can help clarify any questions.

**Comment by ryanwaits** [comment]
closing as this will be addressed in the redesign of sidebar nav https://github.com/hirosystems/docs/issues/487
