### ISSUE TITLE
Add Platform Office Hours CTA

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/docs#346]
A new CTA/link will be created by @max-crawford and once we have it, we need to add a new link/button in the [Hiro Platform docs](https://docs.hiro.so/platform/overview).

Context: https://www.notion.so/hiropbc/1-1-Calls-93c0c4cfb2d14fd49a63617e7d03e989?pvs=4#ddbea1a287064b74936c6050c3dfa7f3

@eugeniadigon: Once we have the CTA, it'd be great to have your blessing on the brand designs; Docs can follow your lead.

FYI: @andromeda995

**Comment by sabbyanandan** [comment]
@max-crawford: Could you share the CTA link? We can add it to the Hiro Platform's overview page in the Docs. Thanks!

**Comment by max-crawford** [comment]
One challenge here is that there are two CTA links.

Your office hours, Sabby: https://calendly.com/sabbyanandan/platform-office-hours
And Max's: https://calendly.com/max-office-hours/15min

In Iterable, I have this set up as a random split, where 50% of users see one URL, the other 50% the other. Not sure how you want to approach it in docs (I'm guessing docs don't have the ability to split traffic).

The simplest approach is for one of you to own office hours (at least in docs), and we just show that singular URL. Calendly itself doesn't offer calendar routing (e.g. let customer pick a time and the tool routes to whichever of you is free) unless you have a CRM integration (eg Salesforce, Hubspot). There might be other workarounds, but I'd need to dig in further to find them.

**Comment by sabbyanandan** [comment]
Thanks, @max-crawford! 

@LakshmiLavanyaKasturi: I would use my link for now; we can revisit based on the response.  

Here's the text for the NOTE:

> If you’d like guidance or help with Hiro Platform, you can also speak with one of our team members directly on a call.
> --
> [Schedule a Call](https://calendly.com/sabbyanandan/platform-office-hours)

**Comment by LakshmiLavanyaKasturi** [comment]
https://github.com/hirosystems/docs/pull/371

**Comment by LakshmiLavanyaKasturi** [comment]
Changes are merged. Marking this done.
