### ISSUE TITLE
Change Developer Survey button to banner

### ISSUE THREAD

**Issue by smcclellan** [hirosystems/docs#351]
Design to come from @eugeniadigon.

Related to: https://github.com/hirosystems/docs/pull/348

**Comment by eugeniadigon** [comment]
Here's the design for the marquee banner: https://www.figma.com/file/Gc7LJh8NWRvSOWQMnxmCm5/Hiro-Docs-2023?type=design&node-id=402%3A354&t=k9c6UDZKNFGB0N1W-1

There's an ideal option:
![Dev survey-1](https://github.com/hirosystems/docs/assets/78865845/54dae573-9f27-464f-aaf6-00c0de6597b2)

And there's also a simpler version in case there are technical limitations:
![Dev survey](https://github.com/hirosystems/docs/assets/78865845/886ad800-c2b5-4690-9576-a8bbd251982e)


As a suggestion, you could also repurpose this banner in the future to report incidents, if desired:

![Warning](https://github.com/hirosystems/docs/assets/78865845/8086e28e-2bc9-4f35-b728-fb120a5e1a94)

**Comment by hugocaillard** [comment]
@janniks I started 10 min ago 😬
But I'll remember to make sure you're in the loop next time
