### ISSUE TITLE
Add how-to guide on API key

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/docs#355]
Under the ["How-to Guides"](https://docs.hiro.so/stacks-blockchain-api/how-to-guides/how-to-install-stacks-cli), add a new guide describing the steps and sample code on how to use the API keys to interact with Stacks Blockchain API.

Eventually, we can expand it to Ordinals and Metadata API, also.

**Comment by timstackblock** [comment]
STEP 1: First submit a request an API key from Charlie and the devops team

STEP2: If you meet the criteria and your request is approved Devops will give you an api key in the following format
**NAME: x-hiro-api-key  
VALUE:Nabcs1234efg56789**

STEP 3: These values must be added to the REQUEST HEADER of every request sent to the api like in the picture below.

STEP 4: The API key essentially disables Istio rate-limiting for your request if the header is edited correctly with your API key

<img width="989" alt="Screen Shot 2023-05-18 at 6 11 38 PM" src="https://github.com/hirosystems/docs/assets/49165468/fe21d400-8895-4972-a525-bfffd449abb2">
<img width="742" alt="Screen Shot 2023-05-18 at 6 11 14 PM" src="https://github.com/hirosystems/docs/assets/49165468/a6eb2793-1e4d-4967-8b8a-06e36d843270">

**Comment by LakshmiLavanyaKasturi** [comment]
https://github.com/hirosystems/stacks-blockchain-api/pull/1667

**Comment by LakshmiLavanyaKasturi** [comment]
https://github.com/hirosystems/docs/pull/381

**Comment by LakshmiLavanyaKasturi** [comment]
Marking this as complete.
