### ISSUE TITLE
Update contributors-guide

### ISSUE THREAD

**Issue by ShivamPandey00** [hirosystems/docs#357]
Hello,

I noticed that the Contributor Guide currently does not include a "Before Development" section. This section could be beneficial for newcomers who want to contribute to the project but aren't sure where to start.

I suggest adding a "Before Development" section that includes the following:

1. Prerequisites: Mention that contributors need to have certain dependencies installed on their local machines (e.g., Yarn) before they can effectively contribute to the project.
2. Instructions on how to fork the repository.
3. Steps to clone the forked repository to their local machine.
4. Guide on how to install the project locally, including setting up the development environment.

I believe this would make the Contributor Guide more complete and helpful. 

Thank you for considering my suggestion.

**Comment by LakshmiLavanyaKasturi** [comment]
Thank you for your suggestion. Highly appreciated!

**Comment by coderdeadpool** [comment]
@LakshmiLavanyaKasturi Shall i create the pull request ?

**Comment by LakshmiLavanyaKasturi** [comment]
> @LakshmiLavanyaKasturi Shall i create the pull request ?

Sorry for the delay in responding. Please create a pull request. Thanks!

**Comment by LakshmiLavanyaKasturi** [comment]
PR: https://github.com/hirosystems/docs/pull/370 is merged. Hence marking this item as complete.
