### ISSUE TITLE
Getting started: How to use and review prints/logs

### ISSUE THREAD

**Issue by agraebe** [hirosystems/docs#36]
We received feedback that a developer wanted to print/log via Clarity but didn't understand if/how it is possible. We could add a small example to one of our Clarinet tutorials that points out to Clarity can be used to log something and how it can be reviewed using Clarinet and/or the API

**Comment by LakshmiLavanyaKasturi** [comment]
Getting started with Clarity language is outside the scope of Hiro Docs.https://docs.stacks.co/docs/tutorials/hello-stacks#clarity-book
