### ISSUE TITLE
Subnets demo app documentation

### ISSUE THREAD

**Issue by LakshmiLavanyaKasturi** [hirosystems/docs#364]
Repo: https://github.com/hirosystems/subnet-demo-app

**New How-to guide:**

 - [] Add a How-to guide to use the Subnet demo app.
 - [] Add a link to the demo video: https://www.youtube.com/watch?v=FHKf-9C0LoI.
 - [] Add a screenshot of the Clarinet integrate command output for block 9.
 - [] Add prerequisites "clarinet latest version is required".

**Update the existing readme:**

 - [] Add the following lines to the top of the readme. 
            The project demonstrates some of the capabilities of subnets through a simple hypothetical NFT marketplace where minting, listing and offers happen on L2. This demo app showcases how to mint NFTs, list, transfer, and withdraw them from the subnet back to the mainchain. This is a demo application made to illustrate how wallets, exchanges and developer teams can leverage subnets in their applications.
 - [] Add a link to the demo video: https://www.youtube.com/watch?v=FHKf-9C0LoI

**Comment by sabbyanandan** [comment]
Perhaps add this demo under https://docs.hiro.so/example-apps instead of the Subnets product page.

**Comment by LakshmiLavanyaKasturi** [comment]
https://github.com/hirosystems/subnet-demo-app/pull/1

**Comment by LakshmiLavanyaKasturi** [comment]
Closing this issue as the readme is updated in the PR:https://github.com/hirosystems/subnet-demo-app/pull/1.
