### ISSUE TITLE
Document the default rate limiting rules for Ordinals and Metadata APIs

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/docs#365]
Similar to https://docs.hiro.so/stacks-blockchain-api/how-to-guides/how-to-query-stacks2.0-blockchain#rate-limiting, let's also capture the default rules for the Ordinals and Metadata API.

This would mean we need to add Ordinals API to the left nav. And we already have a left nav for Metadata API, so add another sub-page under it for rate limits.

**Comment by LakshmiLavanyaKasturi** [comment]
Ordinals: https://github.com/hirosystems/ordinals-api/pull/89
Metadata API: https://github.com/hirosystems/token-metadata-api/pull/159

**Comment by LakshmiLavanyaKasturi** [comment]
Done.
