### ISSUE TITLE
Clarinet: How to set up and use accounts defined in a toml file

### ISSUE THREAD

**Issue by agraebe** [hirosystems/docs#37]

**Comment by LakshmiLavanyaKasturi** [comment]
Sabby, I am not able to find a configuration toml file in Clarinet repo. Can you add details on where I can find that config file to this user story to pick it up?

**Comment by sabbyanandan** [comment]
Hi, @LakshmiLavanyaKasturi. When creating a new project, you will notice multiple `.toml` files under the `settings` directory, where each file points to devnet, testnet, and mainnet specific configurations. At least in `Devnet.toml`, you will also see the accounts, the seed phrases and the initial balances.

A few concrete things to document:

1- It'd be useful to highlight the default configurations in Devnet, and how one can use those when using the `clarinet console` or when unit testing the contracts locally. 

2- Furthermore for Testnet/Mainnet, we can also highlight how to define new accounts. Like, what to change in the `Testnet.toml` or `Mainnet.toml`.

3- There are many other [new configurations in README](https://github.com/hirosystems/clarinet#getting-started-with-clarinet), which needs to be captured in docs. I'd recommend finding a way to import sections from the `README.md`  in docs as opposed to duplicating (relates to https://github.com/hirosystems/docs/issues/77).

@obycode / @lgalabru: Any other thoughts?

**Comment by LakshmiLavanyaKasturi** [comment]
Relates to https://github.com/hirosystems/clarinet/issues/478
