### ISSUE TITLE
Clarinet and Stacks JS - Improve Deploy contracts, Angular authenticator and Authentication docs

### ISSUE THREAD

**Issue by LakshmiLavanyaKasturi** [hirosystems/docs#379]
We got thumbs-down feedback for the following documents in the Hiro docs. This issue is to find gaps and update the content, examples, and code snippets for the following articles.

1. [Deploy contracts](https://docs.hiro.so/clarinet/how-to-guides/how-to-deploy-contracts)
2. [Angular authenticator](https://docs.hiro.so/stacks.js/how-to-guides/how-to-use-stacks-connect-with-angular)
3. [build-apps/Authentication](https://docs.hiro.so/stacks.js/feature-guides/authenticate-users-with-connect)

![Image](https://github.com/hirosystems/docs/assets/55154433/9bac746d-41a1-47f3-b2dc-e0f4b00843c6)

@hugocaillard  and @janniks can help with more information.

**Comment by haszankauna** [comment]
Hi @LakshmiLavanyaKasturi could you please expand on this

**Comment by LakshmiLavanyaKasturi** [comment]
@haszankauna, Thanks for your question. This issue is to improve the following documents based on the Thumbs down feedback from the community.

Deploy contracts
Angular authenticator
build-apps/Authentication
