### ISSUE TITLE
[Ordinals API] request: Overview page explaining the different APIs and what you use them for

### ISSUE THREAD

**Issue by elenananana** [hirosystems/docs#389]
Hi! there are seven API endpoints for ordinals API. Is it possible to add an Overview page like the Blockchain API overview page? Thanks!

https://docs.hiro.so/stacks-blockchain-api/overview

**Comment by LakshmiLavanyaKasturi** [comment]
Thanks for the request. We already have an issue being tracked, and it is in progress. https://github.com/hirosystems/docs/issues/380. Closing this as a duplicate.
