### ISSUE TITLE
Enable Google Analytics

### ISSUE THREAD

**Issue by agraebe** [hirosystems/docs#39]
Our docs currently use Fathom for analytics. We decided to move to Google Analytics. As part of that we need to replace the tracking code.

Once we get closer to work on this issue, we can create the project ID that should be used for tracking. The GA property needs to be configurated appropriately and all stakeholders should be invited.

**Comment by pgray-hiro** [comment]
After further discussion we decided to enable Segment analytics as a passthrough to GA.
