### ISSUE TITLE
Add subnet maininet resources to docs

### ISSUE THREAD

**Issue by elenananana** [hirosystems/docs#390]
![Screenshot 2023-06-30 at 5 06 44 PM](https://github.com/hirosystems/docs/assets/62673553/c377dbb4-9bfb-49e9-991e-d59ebfdd4299)

Add Subnet Participants, Miner Incentives + Resources to Docs

**Comment by LakshmiLavanyaKasturi** [comment]
PR: https://github.com/hirosystems/stacks-subnets/pull/316
PR: https://github.com/hirosystems/stacks-subnets/pull/318

The above PR's are ready for review. Please let me know if there is more Subnet doc updates required. Thanks! @saralab @jbencin @obycode

**Comment by LakshmiLavanyaKasturi** [comment]
Docs PR: https://github.com/hirosystems/docs/pull/401. 

@jbencin and @saralab, I see a few other doc requests in this issue. 1. Miner incentives + resources 2. Technical documentation for running a subnet. Please let me know if I am missing something here. Thanks!

**Comment by LakshmiLavanyaKasturi** [comment]
[Per conversations on Slack](https://hiropbc.slack.com/archives/C04HLNRA3HA/p1689115913791519), I am marking this issue as complete.
