### ISSUE TITLE
mimetype image/svg+xml is missing

### ISSUE THREAD

**Issue by 0xcielo** [hirosystems/docs#399]
In your api https://api.hiro.so/ordinals/v1/inscriptions you can't filter for mimetype image/svg+xml. Is it normal?

**Comment by LakshmiLavanyaKasturi** [comment]
Thanks for your question! I am looking into it. I will update this issue as soon as I find more information.

**Comment by LakshmiLavanyaKasturi** [comment]
@0xcielo: You can filter mime_type using svg images. Here is the right way to use it: https://api.hiro.so/ordinals/v1/inscriptions?mime_type=image/svg%2Bxml. Please let me know if you need more help. Thanks!

**Comment by LakshmiLavanyaKasturi** [comment]
@0xcielo: Trying to follow up to see if I can help in any way. Please don't hesitate to close this issue if you find the above information helpful. Thanks!

**Comment by LakshmiLavanyaKasturi** [comment]
Closing this issue @0xcielo. Please feel free to re-open it anytime. Thanks!
