### ISSUE TITLE
Subnets: Update docusaurus config to point to master

### ISSUE THREAD

**Issue by LakshmiLavanyaKasturi** [hirosystems/docs#402]
Change the lines of code related to Subnets to point to master instead of develop.

Example: This link  https://raw.githubusercontent.com/hirosystems/stacks-subnets/develop/docs/feature-guides/ will change to https://raw.githubusercontent.com/hirosystems/stacks-subnets/master/docs/feature-guides/

**Comment by sabbyanandan** [comment]
This is invalid; not required.
