### ISSUE TITLE
Chrome browser: Token metadata API doesn't expand to show the available API's on selecting Tokens.

### ISSUE THREAD

**Issue by LakshmiLavanyaKasturi** [hirosystems/docs#403]
https://docs.hiro.so/metadata. 

This seems to be working fine on Safari. I see the issue on the Chrome browser.

https://github.com/hirosystems/docs/assets/55154433/49bf6bb4-17ca-4612-8c92-ba596ff9f7bc

**Comment by janniks** [comment]
Works on my machine, but I fixed a scroll issue that only occurs when loading the site directly (via link), but not when loaded via the navbar. #404
