### ISSUE TITLE
Remove `$` char from all CLI commands

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/docs#409]
The copy-to-clipboard feature around the code and CLI commands copies the "entire text", including the `$` char at the beginning. Let's remove the character from all commands, so devs won't have copy-paste, and manually remove the `$` before running the command locally.

Alternatively, ignore the `$` char from the copy-to-clipboard feature (if possible).

**Comment by LakshmiLavanyaKasturi** [comment]
Fixed in https://github.com/hirosystems/clarinet/pull/1091

**Comment by LakshmiLavanyaKasturi** [comment]
Fixed in https://github.com/hirosystems/docs/pull/410
