### ISSUE TITLE
Clarinet test revamp - docs to reflect the changes

### ISSUE THREAD

**Issue by LakshmiLavanyaKasturi** [hirosystems/docs#412]
Depends on https://github.com/hirosystems/clarinet/issues/1065.

To work with @hugocaillard

**Comment by Bhardwaj-Himanshu** [comment]
Hi @hugocaillard @LakshmiLavanyaKasturi , let me know if I could help you guys down on jotting down some docs simaltaneously as the work in progress is being made!
And resources from where I could start adding information to things, except the contributing guide and setting up the project locally!
(Pardon me for the multiple tags)

**Comment by LakshmiLavanyaKasturi** [comment]
@hugocaillard, Please update this issue when you have some content ready to publish to docs. @Bhardwaj-Himanshu, We will keep you posted. Thanks for your interest.

**Comment by hugocaillard** [comment]
@LakshmiLavanyaKasturi Depending on my progress, there's a possibility that the work on docs _could_ start next week, but it'll be most likely be for the beginning of September

**Comment by Bhardwaj-Himanshu** [comment]
I'll be dropping my small watch cat here, then!(pun intended)
Thanks @LakshmiLavanyaKasturi @hugocaillard

**Comment by mefrem** [comment]
Hi @hugocaillard —  checking to see if this Issue is still relevant, or if you've updated the docs to reflect Clarinet's latest changes to `test`.
