### ISSUE TITLE
Normalize API product pages with consistent content model

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/docs#418]
As a continuation to https://github.com/hirosystems/docs/issues/376, per @alexlmiller, we can make a few improvements in the left nav for each "API product" page.

+ Ensure the overview page is consistently laid out with intro, purpose, architecture + design specs. (For instance, for Metadata API, the architecture diagram is inside the how-to guide)
+ Include a link to the API reference guide on each overview page. Capture the developer persona who wants to run their API in their infra and the developer persona preferring to rely on our hosted API. For the latter, in particular, the API Reference guide is a key piece of reference. Currently, it is listed explicitly only in the top-nav menu item.
+ To @alexlmiller, the "Feature Guides" feels like an API reference guide; however, they represent each feature supported in the product. Revise the section titles clearly, so it doesn't confuse end-users.

**Comment by alexlmiller** [comment]
The only other suggestion I'd have is it might be better to rename them as "API - XXXXX" instead of "XXXXX API" so that all the APIs are gathered together and jump out as being APIs

**Comment by LakshmiLavanyaKasturi** [comment]
Thank you for the feedback! @alexlmiller. I will take action and put this plan into motion.

**Comment by LakshmiLavanyaKasturi** [comment]
Token Metadata API - https://github.com/hirosystems/token-metadata-api/pull/176/files

**Comment by LakshmiLavanyaKasturi** [comment]
https://github.com/hirosystems/ordinals-api/pull/180

**Comment by LakshmiLavanyaKasturi** [comment]
I will revisit feature guides to use consistent titles in this issue: https://github.com/hirosystems/docs/issues/437
