### ISSUE TITLE
Remove Youtube image from Clarinet overview

### ISSUE THREAD

**Issue by eugeniadigon** [hirosystems/docs#424]
Please remove this image on https://docs.hiro.so/clarinet/introduction since it shows Hiro's old brand and logo. The link to the youtube playlist should suffice. Also please update the link where it says "Hiro's Youtube channel" to be the link to the playlist (https://www.youtube.com/playlist?list=PL5Ujm489LoJaAz9kUJm8lYUWdGJ2AnQTb) as it is more intuitive to click on a link than to click on an image to open a link.

Thank you
 
<img width="1043" alt="Screenshot 2023-07-26 at 12 10 35" src="https://github.com/hirosystems/docs/assets/78865845/836f6976-b62b-48d8-8375-183166df5719">

**Comment by RajeevDash007** [comment]
@eugeniadigon I want to work on this issue

**Comment by LakshmiLavanyaKasturi** [comment]
@RajeevDash007: Please feel free to [contribute and open a PR](https://docs.hiro.so/contributors-guide). Thanks!

**Comment by RajeevDash007** [comment]
@LakshmiLavanyaKasturi Thank you, can you please guide me to get the file which I should edit to solve this issue, I have tried much to find the file but I am not getting it

**Comment by LakshmiLavanyaKasturi** [comment]
@RajeevDash007, This file is available in the Clarinet repository. https://github.com/hirosystems/clarinet/blob/develop/docs/introduction.md. Please feel free to use the "Edit this page" button at the bottom of the page to submit any changes. 

![image](https://github.com/hirosystems/docs/assets/55154433/5e9efa57-2204-496e-b2b0-c4902a73640a)


Happy to help if you have more questions.

**Comment by RajeevDash007** [comment]
Will raise a PR soon
