### ISSUE TITLE
Clarify the jsonexpected for a block_height chainhook that uses the between operator

### ISSUE THREAD

**Issue by BLuEScioN** [hirosystems/docs#428]
Context:
https://hiropbc.slack.com/archives/C053LE0SN67/p1690571212031469

**Comment by LakshmiLavanyaKasturi** [comment]
PR: https://github.com/hirosystems/chainhook/pull/366. @MicaiahReid Please review.

**Comment by LakshmiLavanyaKasturi** [comment]
The fix is available in [this](https://github.com/hirosystems/chainhook/pull/366) PR. @BLuEScioN, Thanks!
