### ISSUE TITLE
Under Platform, Build Contract, swap out Clarity Camp for Bitcoin Builders Primer

### ISSUE THREAD

**Issue by elenananana** [hirosystems/docs#432]
<img width="960" alt="Screenshot 2023-08-07 at 4 21 18 PM" src="https://github.com/hirosystems/docs/assets/62673553/c2616974-0cd3-42af-b5a7-4e3147a62390">

Tip:
If you are new to Clarity programming, please try the Bitcoin Builders Primer.

Link -> https://start.bitcoinprimer.dev/

**Comment by LakshmiLavanyaKasturi** [comment]
https://github.com/hirosystems/docs/pull/449
