### ISSUE TITLE
Hiro Platfrom: Deploy to Testnet: 'use of unresolved function errors'

### ISSUE THREAD

**Issue by enjoywithouthey** [hirosystems/docs#435]
GM Fam,

I am trying to deploy a contract to testnet using Hiro's deploy platform.  I am getting a series of `use of unresolved function` errors throughout the code.
`int-to-ascii`
`index-of?`
`slice?`

these return the error.  My contract works perfectly in the devnet environment and clarient console.  I can't find any documentation anywhere why this is happening.

An
<img width="1035" alt="Screenshot 2023-08-08 at 11 19 35 AM" src="https://github.com/hirosystems/docs/assets/17732015/594acee0-c7ec-4fc7-a14f-a1ab2fbe3d19">
<img width="1007" alt="Screenshot 2023-08-08 at 11 19 19 AM" src="https://github.com/hirosystems/docs/assets/17732015/8eefbecf-03c6-4d92-8c66-1dc99ec97c41">
y suggestions?

**Comment by LakshmiLavanyaKasturi** [comment]
@beguene @leahjlou, Can you help with this issue? Also, please let me know if this needs to be documented in the Troubleshooting guide. Thanks!
