### ISSUE TITLE
Investigate why broken links are not reported when running the builds

### ISSUE THREAD

**Issue by LakshmiLavanyaKasturi** [hirosystems/docs#455]
Investigate why https://github.com/hirosystems/docs/issues/446 broken link for API-guides is not detected in the build process.

**Comment by sabbyanandan** [comment]
This is happening for local builds, too. We need to understand why the link checker is breaking behavior.

**Comment by sabbyanandan** [comment]
@janniks: Can you have a look at this when you get a chance?

**Comment by janniks** [comment]
Do you have an example? I think some links are ignored in an ignore file.

**Comment by diwakergupta** [comment]
@sabbyanandan @janniks do either of you have instructions on how to run the link checker locally?

**Comment by janniks** [comment]
> ... do either of you have instructions on how to run the link checker locally?

@diwakergupta Not super straightforward, but it looks like we're using https://github.com/becheran/mlc, with the config in `.github/mlc_config.json` (which isn't the format expected for the actual Rust binary).

I'll try to change some configs to maybe improve the link checking. Any specific issue you're running into?

**Comment by diwakergupta** [comment]
@janniks nope, no issues - just trying to knock out docathon tasks :)

I'm actually wondering what this check buys us, considering we already have broken link checks enabled natively in docusaurus: https://docusaurus.io/docs/api/docusaurus-config#onBrokenLinks
