### ISSUE TITLE
Documentation on Clarity values returned from API

### ISSUE THREAD

**Issue by pgray-hiro** [hirosystems/docs#47]
Several developers have complained that the Stacks API returns Clarity values that must be deserialized before they can be used in Javascript frontends. Although Stacks.js does provide the necessary tools for performing this conversion, the details are not well-documented. The documentation should include:

1. The type of Clarity value that each endpoint returns (likely included in the OpenAPI spec doc)
2. Examples of the necessary Stacks.js calls to deserialize each type of value
3. A cheatsheet or quick reference for common endpoints and their returned values
4. An example app that exercises the Clarity to JS value code in Stacks.js

**Comment by markmhx** [comment]
I agree it's a good idea to document all of this. I wonder as well if we should go even deeper at enhance Stacks.js to handle a lot of this automatically.

**Comment by LakshmiLavanyaKasturi** [comment]
Not a priority for us right now. If there is an urgent need, please reopen.
