### ISSUE TITLE
Stacks.js and stacks.js.org in need of more thorough reference documentation (argument signatures, type explanations, etc.)

### ISSUE THREAD

**Issue by mefrem** [hirosystems/docs#471]
Gold standard: reference docs that lists out functions, the function description, and the different parameters to be passed, and what to do with each parameter and what it does

Problem: People will find the relevant function for their desired functionality, but then have to guess and check with individual parameters the end result.

*more notes to be added*

**Comment by sabbyanandan** [comment]
A feedback from dev:

> Another suggestion is to add example under every function in stack.js / it you have a little snippet you can reuse it will simplify the docs.
