### ISSUE TITLE
Explorer section needs update

### ISSUE THREAD

**Issue by andresgalante** [hirosystems/docs#473]
Changes include:

- [x] Rename "Explorer" to "Stacks Explorer" across the docs and on the sidebar
- [x] Remove the mention of `stacks UI` we don't use it anymore and change the description to "The [Stacks Explorer](https://explorer.hiro.so/) is an observability tool that helps users, developers, miners, and investors understand the Stacks Blockchain. It's built with [React](https://reactjs.org/), [next.js](https://github.com/zeit/next.js) and [Chakra UI](https://chakra-ui.com/)."
- [x] Follow the [contribution guidelines](https://github.com/hirosystems/explorer/blob/main/.github/CONTRIBUTING.md) to improve the `Build Explorer` section
- [x] If we improve the Build Explorer, I don't think we need a getting started, we should probably have one or the other. Either way the Getting started section is also out of date, and there is more info in the contribution guidelines

**Comment by elenananana** [comment]
@andresgalante 

> Rename "Explorer" to "Stacks Explorer" across the docs and on the sidebar

I think for this the explorer repo has to be renamed Stacks Explorer
<img width="975" alt="Screenshot 2023-10-05 at 9 06 29 AM" src="https://github.com/hirosystems/docs/assets/62673553/63771fc0-51a0-4b5f-bf6d-b314e22562b1">

I tried to go into the docusaurus config file and got a little lost. @sabbyanandan - can you confirm I am understanding that correctly?

I submitted changes to remove stacks UI and update the description.

I'll book some time with Andy to update the Getting started section. @He1DAr and I discussed making the Getting Started guide detailed/ updated instructions for running/ building an explorer locally, and adding a feature guide for the sandbox. LMK if you disagree!

**Comment by ryanwaits** [comment]
https://github.com/hirosystems/docs/pull/558
