### ISSUE TITLE
Possible Duplicate on Running Stacks API with Docker

### ISSUE THREAD

**Issue by alexlmiller** [hirosystems/docs#480]
Are https://docs.hiro.so/stacks-blockchain-api/how-to-guides/how-to-run-stacks-blockchain-api-docker and https://docs.hiro.so/stacks-blockchain-api/how-to-guides/how-to-use-docker-with-Stacks-blockchain-api the same thing?

If so should remove the one with less helpful content

**Comment by rafaelcr** [comment]
Solved via https://github.com/hirosystems/stacks-blockchain-api/pull/1716

**Comment by csgui** [comment]
Just a remark.... removing that entry caused an issue with Docusaurus starting process. It was trying to find the documentation linked at the `stacks-blockchain-api`. Fixed by: https://github.com/hirosystems/docs/pull/510

@alexlmiller Seems that this issue here can be closed. :-) 

Cheers!
