### ISSUE TITLE
Fix link

### ISSUE THREAD

**Issue by losatnick** [hirosystems/docs#482]
Link is not clickable for "starting the API server" 

[
](https://docs.hiro.so/stacks-blockchain-api/getting-started)

**Comment by csgui** [comment]
Hey @losatnick !

Was not able to find the issue you mentioned. Could you please add more context? Thanks!

**Comment by losatnick** [comment]
Ah! So I already went in and edited this link to make it clickable (its #4 on this page-[-](https://docs.hiro.so/stacks-blockchain-api/getting-started) ; doesn't look like the change has been approved yet.
