### ISSUE TITLE
Broken link --  Page not found -- Using Clarity Values

### ISSUE THREAD

**Issue by losatnick** [hirosystems/docs#485]
Under the section " Using Clarity Values" the word "Clarity Value" is hyperlinked, but the link sends a page not found message. 
[
](https://docs.hiro.so/stacks-blockchain-api/feature-guides/use-clarity-values)

**Comment by csgui** [comment]
Hi @losatnick !

The mentioned link seems to be working properly. Can we close this issue?

**Comment by MicaiahReid** [comment]
@csgui, the link still looks broken to me! I'll take this one.
