### ISSUE TITLE
Broken link -- Page not found --using clarity values --> "response value utilization"

### ISSUE THREAD

**Issue by losatnick** [hirosystems/docs#486]
Link to "response value utilization much simpler" sends to a 'page not found'
[
](https://docs.hiro.so/stacks-blockchain-api/feature-guides/use-clarity-values)

**Comment by csgui** [comment]
Hi @losatnick !

The mentioned link seems to be working properly. Can we close this issue?

**Comment by losatnick** [comment]
The link still isn't working for me - I've attached a screenshot of the section im referencing 
<img width="1004" alt="Screen Shot 2023-10-03 at 9 27 26 AM" src="https://github.com/hirosystems/docs/assets/140840497/820346ce-131d-4b68-9029-704045fe4808">

**Comment by csgui** [comment]
Are you following this link? https://docs.hiro.so/get-started/stacks-blockchain-api#using-clarity-values

**Comment by losatnick** [comment]
Ah yeah - the second link is the one that I was viewing and discovered the broken link

**Comment by losatnick** [comment]
All the docs im reviewing I'm getting to from hiro.so --> docs

**Comment by MicaiahReid** [comment]
Fixed by https://github.com/hirosystems/stacks-blockchain-api/pull/1726
