### ISSUE TITLE
Update sidebar, navbar, footer and homepage

### ISSUE THREAD

**Issue by eugeniadigon** [hirosystems/docs#487]
Working file: https://www.figma.com/file/WYxzBZubEGwbbzFq79eNim/Docs---Nav-Updates?type=design&node-id=0%3A1&mode=design&t=KpINGR5mxXpnfXzx-1

Design tasks:

- [x] Update Sidebar with Ordinals / Stacks product architecture, following hiro.so logic to have consistency cross-organization
- [ ] Update homepage to have a "Get started" / Learn & build focus / Useful quick links
- [x] Clear up side bar when viewing specific product
- [x] Clear-up footer
- [x] Other navbar updates: Move roadmap, improve search bar
- [ ] Some context for homepage edits https://www.notion.so/hiropbc/Docs-Getting-Started-Notes-1c835ca4a2274767806a1bc8c8b06771

**Comment by elenananana** [comment]
oh I made a duplicate issues regarding top nav and getting started copy. I can add those here.

**Comment by elenananana** [comment]
These are the two related issues I believe.
#512
#513

**Comment by eugeniadigon** [comment]
The design is ready for Sidebar, Navbar, and Footer updates, [link](https://www.figma.com/file/WYxzBZubEGwbbzFq79eNim/Docs---Nav-Updates?type=design&node-id=0%3A1&mode=design&t=KpINGR5mxXpnfXzx-1)

<img width="1440" alt="NavBar" src="https://github.com/hirosystems/docs/assets/78865845/9243c5c8-44cd-4f8a-a89c-0fee96f5a4ab">

<img width="1440" alt="Hover states" src="https://github.com/hirosystems/docs/assets/78865845/02c753bf-3812-4a76-85ab-65db00769ef7">

<img width="1440" alt="Product NavBar" src="https://github.com/hirosystems/docs/assets/78865845/7e7b5b92-0341-48f8-951f-11a341e9cd29">

**Comment by ryanwaits** [comment]
@eugeniadigon these look great to me! i think before we sign off and prioritize this with engineering we need to finalize whether or not we are going to move our docs to [mintlify](https://mintlify.com/) where these designs can still be implemented

will update here soon

**Comment by ryanwaits** [comment]
@eugeniadigon discussed with the rest of the devlrel team and they agree with adding Hiro Hacks to the updated docs structure laid out in your designs 🎉 

my 2c:
- adding Hiro Hacks to the sidebar nav below where the current `Hiro Platform` link is would be ideal.
- per the product page for Hiro Hacks, I would suggest a `Getting Started` and then a new `Hacks` section where the titles of each hack would be listed below.

**Comment by eugeniadigon** [comment]
> @eugeniadigon discussed with the rest of the devrel team and they agree with adding Hiro Hacks to the updated docs structure laid out in your designs 🎉
> 
> my 2c:
> 
> * adding Hiro Hacks to the sidebar nav below where the current `Hiro Platform` link is would be ideal.
> * per the product page for Hiro Hacks, I would suggest a `Getting Started` and then a new `Hacks` sidebar section where the titles of each hack would be listed below.

With this update, I propose the following architecture (also updated on Figma):

<img width="1440" alt="sidebar" src="https://github.com/hirosystems/docs/assets/78865845/e0bd2fad-6826-4c85-b693-b7d938954b75">

**Comment by eugeniadigon** [comment]
I'd like to keep this issue open to be able to reference back to these designs if that's ok

**Comment by ryanwaits** [comment]
@eugeniadigon feel free to open this back up
