### ISSUE TITLE
Standardize architectural diagrams style

### ISSUE THREAD

**Issue by ginny-d** [hirosystems/docs#488]
- Gather all images
- Create a unique consistent style

Examples (of what shouldn't happen):

![image](https://github.com/hirosystems/docs/assets/78865845/e7d9f0ce-a7d5-4c1c-8028-c5eae8e2975b)

![image](https://github.com/hirosystems/docs/assets/78865845/67650fe5-1a9d-466e-a4df-f06a9f898dfc)

![image](https://github.com/hirosystems/docs/assets/78865845/7b9595a4-06d1-416d-b0e5-77a326f042a3)

![image](https://github.com/hirosystems/docs/assets/78865845/672c4bf6-49d1-4c61-85ab-54439700672e)

**Comment by eugeniadigon** [comment]
Found diagrams:

https://docs.hiro.so/stacks-blockchain-api/overview
https://docs.hiro.so/token-metadata-api/overview

**Comment by elenananana** [comment]
<img width="1114" alt="Screenshot 2023-10-12 at 10 56 13 AM" src="https://github.com/hirosystems/docs/assets/62673553/5c31a00b-2ce6-47f4-8595-540e8fbb2280">

another one

**Comment by ryanwaits** [comment]
closing, combined with https://github.com/hirosystems/docs/issues/502

**Comment by eugeniadigon** [comment]
![image](https://github.com/hirosystems/docs/assets/78865845/d48dd867-3508-419c-a46a-c42abae5b491)

**Comment by eugeniadigon** [comment]
> closing, combined with #502

Reopening, this issue addresses graphs already in existence. The other issue requests new graphs.

**Comment by eugeniadigon** [comment]
@ryanwaits Here are the updated architecture diagrams that are currently on Docs. These are on SVG so they work both on light and dark mode. 

![StacksAPI-Diagram](https://github.com/user-attachments/assets/17322c35-3f1e-4210-91d9-164421946fb2)
----------
![TokenAPI-Diagram1](https://github.com/user-attachments/assets/d93bb6a4-c9f2-4a47-ad73-943dac43e7c2)
----------
![TokenAPI-Diagram2](https://github.com/user-attachments/assets/d64345bb-f577-4a57-8f55-d6ac5fa8cf1e)

These graphs can be found at https://docs.hiro.so/stacks/api/architecture and https://docs.hiro.so/stacks/token-metadata-api/architecture

I didn't find any other graphs on the site, but let me know if I missed any!
