### ISSUE TITLE
[nit] .sh is not .js updating billboard script

### ISSUE THREAD

**Issue by dcsan** [hirosystems/docs#49]
the docs for billboard app

https://docs.hiro.so/example-apps/billboard#updating-the-billboard-value

refer to using a shell script

> you can use the update-message.sh script in the root 

but in fact it's a `js` script
https://github.com/pgray-hiro/stacks-billboard/blob/main/update-message.js

also might be good to link to it directly (tho it might move :( )

**Comment by agraebe** [comment]
thanks so much for tall the issues @dcsan!
