### ISSUE TITLE
Update the Architecture diagram under API Overview to fit Hiro's branding 

### ISSUE THREAD

**Issue by saralab** [hirosystems/docs#503]
This architecture diagram under API overview is ready for a redesign and update to match Hiro branding: https://docs.hiro.so/stacks-blockchain-api/overview
https://docs.hiro.so/token-metadata-api/overview

**Comment by eugeniadigon** [comment]
Duplicate issue https://github.com/hirosystems/docs/issues/488 - Closing this one
