### ISSUE TITLE
Standardize Overview pages across products

### ISSUE THREAD

**Issue by saralab** [hirosystems/docs#505]
- Let's bring consistency across the Overview pages. 
- Start by creating a Template that can be reused - for both existing and new Products. 

Few pointers (not final) , let's go back to the drawing board and 
- Start with a blurb on what the Product Does 
- How It Works : Include a standard Architecture or Flow Diagram Template [ #503 ] 
- Ensure it covers: What, Why, How in detail

**Comment by alexlmiller** [comment]
@saralab @ryanwaits I think we already have a standardized template for Github READMEs right? If not, we should do the same for those

**Comment by saralab** [comment]
Yes we do, ReadMes are crisp and short, and agree they need to be updated too. Updated the issue to include both.
