### ISSUE TITLE
Replace "Getting Started" copy on Docs Landing page

### ISSUE THREAD

**Issue by elenananana** [hirosystems/docs#512]
### Start building on Bitcoin Layers
Integrate Stacks and Ordinals in your application with Hiro’s tools. Explore API references, feature guides and tutorials.

Notes in [notion](https://www.notion.so/hiropbc/Docs-Getting-Started-Notes-1c835ca4a2274767806a1bc8c8b06771?pvs=4)

**Comment by diwakergupta** [comment]
@elenananana are you working on this? Also from the linked Notion page it wasn't clear if there's an agreed upon set of changes.

At the very least I'd like to tweak the language and links so the page is accurate and high impact. I can take a crack at that, but wanted to check with you first.

**Comment by ryanwaits** [comment]
ive added this as a task item to https://github.com/hirosystems/docs/issues/487
