### ISSUE TITLE
Replace "Roadmap" with "Log into Platform" button in the top nav

### ISSUE THREAD

**Issue by elenananana** [hirosystems/docs#513]
<img width="1520" alt="Screenshot 2023-10-03 at 10 31 52 AM" src="https://github.com/hirosystems/docs/assets/62673553/81f72f5d-76a8-4244-9e7f-18d1cc271165">

**Comment by ryanwaits** [comment]
@elenananana are we saying just get rid of the roadmap section entirely? or relocate that link to somewhere else

**Comment by ryanwaits** [comment]
new docs launch solves this
