### ISSUE TITLE
Ensuring all code examples in Stacks.js > Feature Guides are correct

### ISSUE THREAD

**Issue by mefrem** [hirosystems/docs#520]
(Twin issue to https://github.com/hirosystems/docs/issues/519)

For purposes of avoiding duplicate effort, this Issue is to signify that @ryanwaits is working through "Feature Guides" portion of the Stacks.js documentation to ensure code validity, and make any further changes or issues as needed.

**Comment by ryanwaits** [comment]
adding https://github.com/hirosystems/docs/pull/528 for reference here
