### ISSUE TITLE
Make a better differentiation between API Docs <> API References

### ISSUE THREAD

**Issue by eugeniadigon** [hirosystems/docs#521]
At first glance, these pages look the same, although they serve different purposes:

https://docs.hiro.so/stacks-blockchain-api/overview
https://docs.hiro.so/api

https://docs.hiro.so/ordinals-api/overview
https://docs.hiro.so/ordinals

I would adjust the reference pages making it visually clear that they are API references. I can work on a proposal soon.

**Comment by ryanwaits** [comment]
solved with new docs
