### ISSUE TITLE
Remove acronym "tx" and replace with "transaction" on Stacks.js FAQ page

### ISSUE THREAD

**Issue by losatnick** [hirosystems/docs#522]
Referencing Priority 2 - grammar & language; avoiding industry jargon

**Comment by csgui** [comment]
FIxed by this  [PR](https://github.com/hirosystems/stacks.js/pull/1570) on Stacks.js repo.

**Comment by ryanwaits** [comment]
https://github.com/hirosystems/docs/pull/558
