### ISSUE TITLE
Stacks.js Troubleshooting Page - is there really only one "common pitfall"?

### ISSUE THREAD

**Issue by losatnick** [hirosystems/docs#523]
Priority 1 - Accuracy

It seems to me that if we have a section for troubleshooting, there would or should be more than one common pitfall? I assume devs might visit that page with more than one possible issue, right? Or am I wrong?

**Comment by ryanwaits** [comment]
good call out - we can move this to part of the redesign initiative as some of these "common pitfalls" probably don't need it's own dedicated page, but rather added into sections where the context makes more sense
