### ISSUE TITLE
Idea: Include doc page for sBTC, possibly on sidebar, for collection of sBTC resources, tutorials, etc.

### ISSUE THREAD

**Issue by mefrem** [hirosystems/docs#526]
Given the expansive impact of sBTC and the Nakamoto upgrade to the Stacks ecosystem, might it be worthwhile to have a Hiro-centric docs page for sBTC and Nakamoto changes? Some ideas for what to include

- Links to the tutorial for getting started developing with the sBTC developer release
- Links to the [official documentation](https://stacks-network.github.io/sbtc-docs/introduction.html)
- Overview of how our products might support sBTC development, with links out to other portions of our docs (Clarinet, Stacks.js, etc.)

**Comment by ryanwaits** [comment]
we are planning to integrate both nakamoto and sbtc related content into docs as part of q3 initiative, details here are a bit outdated so we can create new updated issues targeting some specifics once we get closer to addressing these
