### ISSUE TITLE
Show last updated timestamp and page author

### ISSUE THREAD

**Issue by agraebe** [hirosystems/docs#53]
We should enable the timestamp and author indicating when and who updated a page. It seems to be a simple configuration: 

- https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#showLastUpdateTime
- https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#showLastUpdateAuthor

**Comment by coderdeadpool** [comment]
Hey @agraebe, Can you please assign this issue to me.

**Comment by diwakergupta** [comment]
> Hey @agraebe, Can you please assign this issue to me.

cc/ @andresgalante

**Comment by andresgalante** [comment]
@coderdeadpool I just did. Thanks for the offer, and let us know if we can help with your contribution

**Comment by coderdeadpool** [comment]
> @coderdeadpool I just did. Thanks for the offer, and let us know if we can help with your contribution

@andresgalante Sure, Thank you

**Comment by LakshmiLavanyaKasturi** [comment]
Not a priority for us right now.
