### ISSUE TITLE
[Clarinet] Add a network table to clarinet docs describing each of the network types and when to use.

### ISSUE THREAD

**Issue by elenananana** [hirosystems/docs#530]
Add a network table to clarinet docs describing each of the network types and when to use.

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-6537c438-7fff-961e-e7b8-57651cd2b0ad"><div dir="ltr" style="margin-left:0pt;" align="left">

Network Type | When to use
-- | --
Simnet |  
Devnet |  
Testnet |  
Mainnet |  

</div></b>

**Comment by ryanwaits** [comment]
https://github.com/hirosystems/docs/pull/558
