### ISSUE TITLE
Improve location of FAQ, Troubleshooting Guides, Dev Resources and Contribution Guidelines in side nav

### ISSUE THREAD

**Issue by elenananana** [hirosystems/docs#532]
Currently FAQ, Troubleshooting Guides, Dev Resources and Contribution Guidelines are all sections that are repeated under each product. 

Recommendation is to move all these sections into their own pages (such as all FAQs in one section, listed out by product vs a separate FAQ page per product). Other ideas mentioned by the team

- Great idea, intuitively I (and I think Devs) Look for Products and then questions within those products. We could have a generic FAQ section for areas that are broader.
- combining Troubleshooting guides in the sidebar with this FAQ page 
- same with “Developer Resources” under each product, links to blog, youtube, and discord. Feels repetitive when those links are easily discoverable.

**Comment by ryanwaits** [comment]
this can be a part of the structural redesign, something resembling a layout like this
<img width="719" alt="Screenshot 2023-10-31 at 3 55 25 PM" src="https://github.com/hirosystems/docs/assets/3207017/cfe595dc-5040-4872-abc3-afb624fcd1e0">

**Comment by ryanwaits** [comment]
closing: close duplicate to https://github.com/hirosystems/docs/issues/506
