### ISSUE TITLE
[typo] under Chainhook -> How-to Guides

### ISSUE THREAD

**Issue by eugeniadigon** [hirosystems/docs#539]
Says "Bitcoind"

<img width="298" alt="Screenshot 2023-10-08 at 19 17 02" src="https://github.com/hirosystems/docs/assets/78865845/dbceced1-aa10-4d1a-a829-24f5f4ae7734">

**Comment by ryanwaits** [comment]
ohh now i know what you were referring to ha! so the service used here is called `bitcoind` (Bitcoin Core daemon), but perhaps we can still change the title for simplicity, since the specifics are called out in the guide itself
