### ISSUE TITLE
Banner: API Rate Limit

### ISSUE THREAD

**Issue by elenananana** [hirosystems/docs#551]
as part of comms for a new API rate limit, I'd like to put a banner up on docs. Ideally the banner goes up once the blog is out, but it can go up anytime if there are other pressing priorities.

@ginny /-/ has this banner preset for announcements/warning, we'd only need to swap colors and icon

**Copy:** Upcoming changes to rate limits for Hiro APIs → Learn more.

https://www.figma.com/file/Gc7LJh8NWRvSOWQMnxmCm5/Hiro-Docs-2023?type=design&node-id=621%3A128&mode=design&t=zuxgF0HQ6JBj9UaB-1

@sabbyanandan @eugeniadigon

**Comment by saralab** [comment]
@ryanwaits Let's split this issue into 2 : 
1. The API rate limit banner which should be good to go as is now 
2. A Warning banner as shown in the designs : This will involve some integration with Status Page and we need to ensure that the banner can auto-update or close when the Issues/Warning is resolved.

**Comment by eugeniadigon** [comment]
@saralab Please refer only to the board shared for this specific task (https://www.figma.com/file/Gc7LJh8NWRvSOWQMnxmCm5/Hiro-Docs-2023?type=design&node-id=621%3A128&mode=design&t=zuxgF0HQ6JBj9UaB-1)

The other Figma board was a previous design made as an example, not meant to be implemented right now

**Comment by ryanwaits** [comment]
based on how the current banner works, we should be able to put up a new one once the blog is posted. it's a hard coded time window so if we have an expected release date of the the rate limit blog + how long we'd like to have the banner exposed, all i'd need are the dates and the expected url for the blog and we should be good to go

**Comment by ryanwaits** [comment]
> @ryanwaits Let's split this issue into 2 :
> 
> 1. The API rate limit banner which should be good to go as is now
> 2. A Warning banner as shown in the designs : This will involve some integration with Status Page and we need to ensure that the banner can auto-update or close when the Issues/Warning is resolved.

@saralab https://github.com/hirosystems/docs/issues/553

**Comment by sabbyanandan** [comment]
Aside from the Banner or however else y'all are thinking about solving this, please also ensure all the three rate-limiting guides are updated to include the supported RPM with and without API Key.

**Comment by saralab** [comment]
> The other Figma board (warning banner) was a previous design made as an example, not meant to be implemented right >now. That being said, if there's capacity to implement this as well, that's good!

I understand that, the ask to create an issue is so we can track that change even if we don't have the bandwidth at the moment.

**Comment by ryanwaits** [comment]
closing: moved additional issues to separate tickets https://github.com/hirosystems/docs/issues/553 and https://github.com/hirosystems/docs/issues/557
