### ISSUE TITLE
Update rate-limiting guides to include the supported RPM with and without API Key

### ISSUE THREAD

**Issue by ryanwaits** [hirosystems/docs#557]
This needs to be done before 11/9

**Comment by elenananana** [comment]
<img width="223" alt="Screenshot 2023-11-06 at 9 40 55 AM" src="https://github.com/hirosystems/docs/assets/62673553/1e9ef57f-c4b3-4ec2-a848-627d143e8928">


currently, rate limits live in the feature guide section of each API. I propose doing a single page with the rate limits for all APIs. Happy to help draft something.

**Comment by ryanwaits** [comment]
merged https://github.com/hirosystems/docs/pull/562
