### ISSUE TITLE
[Platform] Document `clarinet integrate` flow from VS Code

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/docs#563]
Additional context: https://docs.google.com/document/d/1k5X8ATXVY4e2zuUAhRcZ0jPXPwf-BknzS97UwvIbYxg/edit?disco=AAAA_4xuVTM

**Comment by ryanwaits** [comment]
was this issue resolved in the current docs @sabbyanandan ? see[here](https://docs.hiro.so/platform/guides/devnet#starting-and-managing-devnet)

**Comment by sabbyanandan** [comment]
Yeah, this is now covered via the command-line inside VS Code (through a URL output), and then the actual Devnet itself. Thanks for the follow-up.
