### ISSUE TITLE
Postman Collection {{baseUrl}} trailing slash needs to be removed.

### ISSUE THREAD

**Issue by Markeljan** [hirosystems/docs#592]
On [https://docs.hiro.so/api](https://docs.hiro.so/api) the initial postman collection variables includes a trailing / however each example already has a leading / causing none of the endpoints to work.

<img width="908" alt="image" src="https://github.com/hirosystems/docs/assets/12901349/f6108c06-b1e8-46fa-8c23-8fb47d013780">

After removing the trailing / all endpoints work.

**Comment by Markeljan** [comment]
Additionally the links are not rendered as intended.

<img width="1104" alt="image" src="https://github.com/hirosystems/docs/assets/12901349/e53a1662-0da1-42c4-b0f7-16da9d616dbb">

**Comment by ryanwaits** [comment]
fix merged in with pr: https://github.com/hirosystems/stacks-blockchain-api/pull/1791
