### ISSUE TITLE
Clarify the rate-limiting language with additional details

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/docs#593]
**Ask 1:**
The [language written as-is](https://docs.hiro.so/rate-limiting) is entirely correct. However, we can further expand on what "_all Hiro APIs_" means. In this case, a single rate-limiting quota is applied to all 3 public-facing APIs: Stacks Blockchain API, Metadata API, and Ordinals API. 

For instance, if a developer uses either one or all 3 APIs simultaneously. In that case, the entirety of all API traffic will be attributed to a _single default quota_, which would be 50 RPM for unauthenticated and 500 RPM for authenticated traffic, respectively. 

Let's explicitly state this in the docs so it provides further guidance to developers.

-----

**Ask 2:**
In addition to RPM (requests per minute; the primary rate-limiting criteria), we recently introduced secondary rate-limiting criteria in our API infrastructure. Having both kinds is a best practice for any publicly offered API service for added security, better utilization & resource protection, and protecting the API service from abuse.

We want to include a blurb about the secondary rate limit, and in our case, that is 20 RPS (requests per second) for both authenticated and unauthenticated traffic.

**Comment by sabbyanandan** [comment]
@ryanwaits: I would like to request us to clarify the language soon, so I marked it as "urgent" priority. 

cc:/ @CharlieC3 @andresgalante

**Comment by ryanwaits** [comment]
sorry i let this one slip through the cracks, @sabbyanandan 

heres the pr addressing this issue: https://github.com/hirosystems/docs/pull/594
