### ISSUE TITLE
Ordhook server error.

### ISSUE THREAD

**Issue by devlancer412** [hirosystems/docs#615]
I got this error when I tried to use ordhook for backend indexer. Please check this screenshot.
![image](https://github.com/hirosystems/docs/assets/101313445/10dfa848-d58a-4eb3-b787-b9bc0c32260a)

This is my ordhook config
![image](https://github.com/hirosystems/docs/assets/101313445/cbb5fe67-d7d7-456f-b18f-54e55436ead2)

**Comment by ryanwaits** [comment]
@devlancer412 is this still an issue you're running into with the latest Ordhook installed? https://docs.hiro.so/ordinals/ordhook/installation
