### ISSUE TITLE
Expand and clarify the use of post-conditions with examples

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/docs#625]
Context:

> I think I have managed to fix the issues I was having, but a key thing that I noticed was that in order for fungible token post conditions to work, the createAssetInfo function used to create the info must use the fungible-token name as defined in the deployment contract, and not the name of the token from the contract. Simple things like these are easy to miss when coding, and I think a general update of the post condition documentation including more examples would be helpful and in order. It took me a few days to figure this out.

This developer had to trial & error and figure it out, but they figured it out, and kudos to them!
However, this will stump others, so it would help to expand the post-condition examples with this use-case scenario and explain exactly what needs to be set.

**Comment by ryanwaits** [comment]
@sabbyanandan noted: this will be added to the docs revamp
