### ISSUE TITLE
[clarinet] Document the derivation path setting fro deployment

### ISSUE THREAD

**Issue by hugocaillard** [hirosystems/docs#632]
In the manifest, it's possible to specify the derivation path for accounts

```
[accounts.deployer]
mnemonic = "<YOUR PRIVATE TESTNET MNEMONIC HERE>"
derivation = "m/44'/5757'/0'/0/2"
```

https://github.com/hirosystems/clarinet/issues/1376

**Comment by ryanwaits** [comment]
@hugocaillard noted: this will be added to docs revamp

**Comment by ryanwaits** [comment]
currently blocked, ref: https://github.com/orgs/hirosystems/projects/50/views/1?pane=issue&itemId=76412832
