### ISSUE TITLE
[Chainhook] Document chainhook trigger payload

### ISSUE THREAD

**Issue by MicaiahReid** [hirosystems/docs#644]
When a chainhook is triggered, we don't have any documentation on the payload.

This was requested in a discord thread: https://discord.com/channels/621759717756370964/1222070000886616064

**Comment by ryanwaits** [comment]
@MicaiahReid noted: this will be added to new docs revamp

**Comment by ryanwaits** [comment]
ref: https://github.com/hirosystems/docs/pull/724
