### ISSUE TITLE
stacks.js links to docs are 404'ing

### ISSUE THREAD

**Issue by wileyj** [hirosystems/docs#65]
https://docs.hiro.so/intro

any of the links to docs for `stacks.js` are 404ing, i.e. https://blockstack.github.io/stacks.js/modules/transactions.html
![Screenshot 2022-01-21 at 08 08 29](https://user-images.githubusercontent.com/2847772/150560491-1987c8fe-b43a-4092-a531-f2b0b4cd1a37.png)

**Comment by sabbyanandan** [comment]
Apologies for the delay. All of them were addressed already, and remaining will be catch up via https://github.com/hirosystems/docs/pull/76.
