### ISSUE TITLE
API websockets example is out of date

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/docs#66]
The API Websockets example in https://github.com/hirosystems/docs/blob/main/docs/get-started/stacks-blockchain-api.md is out of date when compared to the [API client docs](https://github.com/hirosystems/stacks-blockchain-api/blob/master/client/README.md). We should update it to reflect a more recent example.

Also, the example can be confusing because it's given in the context of Typescript when it's written in JavaScript. We should make clear it's in JS or rewrite it to compile in Typescript.

**Comment by sabbyanandan** [comment]
Relates to #78

**Comment by LakshmiLavanyaKasturi** [comment]
Closing in favor of https://github.com/hirosystems/docs/issues/417
