### ISSUE TITLE
Documentation of the end point for fetching a data-var

### ISSUE THREAD

**Issue by radicleart** [hirosystems/docs#668]
I believe you can get the value of a data var in a clarity contract through API but it hasn't been documented;

E.g. this work but isn't in the official api docs.

```/v2/data_var/${contractAddress}/${contractName}/${dataVarName}```

**Comment by ryanwaits** [comment]
ty for flagging @radicleart we'll add this in our api reference with our next docs release

**Comment by ryanwaits** [comment]
closing as this is part of a larger api update to reference and link to rpc endpoints https://github.com/hirosystems/docs/pull/761
