### ISSUE TITLE
docs: redirect docs.hiro.so/stacks.js/overview

### ISSUE THREAD

**Issue by MicaiahReid** [hirosystems/docs#696]
When I google search "stacks.js", one of the top results links to https://docs.hiro.so/stacks.js/overview, which is now a 404 on the new docs page. I think it would help users to redirect this page somewhere appropriate.

❤️

**Comment by diwakergupta** [comment]
Moved to the docs repo. Also @janniks FYI

**Comment by ryanwaits** [comment]
see https://github.com/hirosystems/docs/pull/697
