### ISSUE TITLE
Add `Cross-Origin-Opener-Policy: same-origin`

### ISSUE THREAD

**Issue by beguene** [hirosystems/docs#717]
All responses from `docs.hiro.so` should have 

` Cross-Origin-Opener-Policy: same-origin`

To prevent Cross-site leaks https://xsleaks.dev/docs/defenses/opt-in/coop/

to verify

`curl -I -L https://docs.hiro.so/`

**Comment by ryanwaits** [comment]
closing https://github.com/hirosystems/docs/pull/718
