### ISSUE TITLE
estimate the cost of a function

### ISSUE THREAD

**Issue by ECBSJ** [hirosystems/docs#729]
::get_costs <exp>
::get_costs (contract-call? .sbtc-token get-decimals)

::toggle_costs
(contract-call? .sbtc-token get-decimals)

also: vitest run -- --coverage --costs

**Comment by ryanwaits** [comment]
currently blocked, ref: https://github.com/orgs/hirosystems/projects/50/views/1?pane=issue&itemId=76412832
