### ISSUE TITLE
Few minor issues on https://docs.hiro.so/stacks/api/info/total-and-unlocked-stx-supply

### ISSUE THREAD

**Issue by diwakergupta** [hirosystems/docs#753]
Description has unnecessary reference to Stacking, which anyways should have been an actual link (vs. in-lining the URL)

<img width="656" alt="Screenshot 2024-09-12 at 1 51 59 PM" src="https://github.com/user-attachments/assets/ddd93e3e-3064-40b9-aafd-093bdcdddaaf">

In the response description, we talk about "target block times" but this endpoint is for STX supply -- looks like copy pasta from a different endpoint?

<img width="393" alt="Screenshot 2024-09-12 at 1 53 26 PM" src="https://github.com/user-attachments/assets/34b850a8-36f6-4be7-b290-82af191bea51">

**Comment by diwakergupta** [comment]
Now that the [API has implemented](https://github.com/hirosystems/stacks-blockchain-api/pull/2092) changes [discussed in this doc](https://www.notion.so/hiropbc/Total-supply-endpoint-af38665d46184408b681e05bbaf1eda0), we should update the documentation accordingly.

In particular, document the new `total_stx_year_2050` field, deprecations of some legacy endpoints etc.

cc/ @zone117x

**Comment by ryanwaits** [comment]
> Description has unnecessary reference to Stacking, which anyways should have been an actual link (vs. in-lining the URL)

> In the response description, we talk about "target block times" but this endpoint is for STX supply

so this copy is still being pulled in with a fresh pull of the OpenAPI spec. i can get this fixed in docs for now, but will need to target the source of the issue to avoid the problem in the future.

> In particular, document the new total_stx_year_2050 field, deprecations of some legacy endpoints etc.

i can update this accordingly

**Comment by diwakergupta** [comment]
> so this copy is still being pulled in with a fresh pull of the OpenAPI spec. i can get this fixed in docs for now, but will need to target the source of the issue to avoid the problem in the future.

@zone117x if the source of truth is in the API repo, can we open an issue to track this?

**Comment by ryanwaits** [comment]
> > so this copy is still being pulled in with a fresh pull of the OpenAPI spec. i can get this fixed in docs for now, but will need to target the source of the issue to avoid the problem in the future.
> 
> @zone117x if the source of truth is in the API repo, can we open an issue to track this?

i can take a look at this and report back - added this to our board https://github.com/orgs/hirosystems/projects/50/views/1?pane=issue&itemId=81806865

**Comment by ryanwaits** [comment]
also this is fixed: https://github.com/hirosystems/docs/pull/761
