### ISSUE TITLE
Import README fragments

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/docs#77]
With Clarinet, stacks.js, and others, we duplicate the install steps in docs instead of maintaining those steps centrally in GitHub READMEs. I couldn't find a way to do that with Docusaurus. There are a few workarounds, including creating a file with `.mdx` and references to the README file, but that may not be as dynamic. 

It'd be helpful to explore a way to maintain the source of truth centrally in a single location.

**Comment by LakshmiLavanyaKasturi** [comment]
This is done,.
