### ISSUE TITLE
Wrong POX version in API docs

### ISSUE THREAD

**Issue by crypt0jan** [hirosystems/docs#778]
**Describe the bug**
On pages such as https://docs.hiro.so/stacks/api/stacking-pool/members, pox3 is still used in example queries instead of pox4 giving different results and confusing developers that are implementing the HIRO API into their software, especially starting developers without knowledge of the difference between pox3 and pox4. 

**To Reproduce**
1. Go to [docs.hiro.so/stacks/api/stacking-pool/members](https://docs.hiro.so/stacks/api/stacking-pool/members)
2. Observe 'pox3' in the example cURL and Javascript request
3. Also observe 'pox3' in the example query at the bottom of the page (see image)
4. Also observe the different end results between the two pox versions (see image)

**Expected behavior**
Update the HIRO API documentation to always use the latest pox contract. 

**Screenshots**

![pox3-1](https://github.com/user-attachments/assets/ba2ba381-0e9d-479d-bd2d-fd4c62abe8e0)
![pox3-2](https://github.com/user-attachments/assets/0162ca79-9891-44ec-a0ab-60caa74d1e36)

**Comment by ryanwaits** [comment]
fixed: https://github.com/hirosystems/docs/pull/761
