### ISSUE TITLE
Revise Tutorials

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/docs#78]
The code snippets embedded in the docs would have to evolve as we tweak the app.

Finally, we must find a way to wrap test harnesses and run those through CI for continuous functionality checks.

Relates to https://github.com/hirosystems/docs/issues/57.

**Comment by LakshmiLavanyaKasturi** [comment]
Moving the Tutorial files to appropriate product locations. Can we do this cleanup as part of the Docusaurus plugin? Relates to https://github.com/hirosystems/docs/issues/126

**Comment by LakshmiLavanyaKasturi** [comment]
Relates to https://github.com/hirosystems/docs/issues/417.

**Comment by LakshmiLavanyaKasturi** [comment]
Closing in favor of https://github.com/hirosystems/docs/issues/417
