### ISSUE TITLE
link to rpc node docs from stacks api page

### ISSUE THREAD

**Issue by ryanwaits** [hirosystems/docs#780]
I think it would be helpful to link to [documentation for the node's API endpoints](https://docs.stacks.co/stacks-101/api) (the /v2/ endpoints) from [our API documentation](https://docs.hiro.so/stacks-blockchain-api). Users won't know (or care) that they are separate, since our API nodes will forward these /v2/ endpoints. This results in difficult discovery for those.

cc @obycode

**Comment by zone117x** [comment]
> Users won't know (or care) that they are separate

I think trying to present the RPC and API docs/endpoints as the same service has caused a lot of problems, and we should separate how they are presented. They are separate services with differing usage, rate limits, performance, etc. 

Similar to how we present some of these other services as separate, there should be something like a `Stacks core RPC`:

<img width="268" alt="image" src="https://github.com/user-attachments/assets/ca5f6c02-99be-4cff-8324-580ffcac4629">

**Comment by ryanwaits** [comment]
> I think trying to present the RPC and API docs/endpoints as the same service has caused a lot of problems, and we should separate how they are presented.

@zone117x i agree with separating these. what do you suggest as the best practice for maintaining this section if we aren't providing any `v2` endpoints in the OpenAPI schema?

In the meantime I guess we could have a callout on the Stacks API overview that links out to the Stacks Docs (https://docs.stacks.co/reference/api) for anyone looking for these endpoints

**Comment by ryanwaits** [comment]
great! ill merge these changes in with the short-term solution and add a new issue for adding the RPC section later

**Comment by ryanwaits** [comment]
fixed: https://github.com/hirosystems/docs/pull/761
