### ISSUE TITLE
Icons and spacing on "help" footer are off

### ISSUE THREAD

**Issue by ginny-d** [hirosystems/docs#786]
Docs:
<img width="546" alt="Screenshot 2024-10-10 at 16 05 09" src="https://github.com/user-attachments/assets/4b5fdadd-3ac7-47dd-8561-da6686681b05">

Design:
<img width="486" alt="Screenshot 2024-10-10 at 16 05 22" src="https://github.com/user-attachments/assets/c79a08a6-1914-435e-807a-9dbc57624c10">

**Comment by rehan-adi** [comment]
Hey, want to work on this
