### ISSUE TITLE
Implement landing page for docs.hiro.so

### ISSUE THREAD

**Issue by ginny-d** [hirosystems/docs#787]
Figma file: https://www.figma.com/design/WYxzBZubEGwbbzFq79eNim/Docs-Working-File?node-id=1005-728&t=M2Q9MWX8ben3D798-1

<img width="1537" alt="Landing-1" src="https://github.com/user-attachments/assets/5c202635-caa7-46a9-a5c1-c7e100b1efed">
<img width="1537" alt="Landing" src="https://github.com/user-attachments/assets/86d436c0-9668-4c6a-a30d-0483f8e35851">

**Comment by rehan-adi** [comment]
@ryanwaits are you working on this ?

**Comment by ryanwaits** [comment]
merged in with https://github.com/hirosystems/docs/pull/795
