### ISSUE TITLE
Add guidance for new Stacks.js support to request accounts

### ISSUE THREAD

**Issue by markmhendrickson** [hirosystems/docs#85]
Per https://github.com/hirosystems/connect/issues/209

We'll need to update the authentication guide to point developers instead to the new functionality for requesting accounts rather than authenticating users per se.

https://docs.hiro.so/build-apps/authentication

**Comment by janniks** [comment]
first refactors [here](https://deploy-preview-89--hiro-docs.netlify.app/build-apps/authentication), with some additional minor changes.

**Comment by LakshmiLavanyaKasturi** [comment]
Closing it. Please reopen if it is still an issue.
