### ISSUE TITLE
Publish rate-limiting characteristics of Hiro's hosted API instance

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/docs#98]
The Hiro's hosted API instance (docs [here](https://docs.hiro.so/api)) are governed by Cloudflare's rate limiting rules to protect the hosted APIs from malicious traffic. As developers continue to use the APIs, they would like to understand the predefined limiting rules for the published endpoints.

More details in Notion [here](https://www.notion.so/hiropbc/Rate-limiting-dd019079b88646719748299ca4206c7d#156a2bc483e642bda86dfd0635ef4687).

**Comment by LakshmiLavanyaKasturi** [comment]
PR created https://github.com/hirosystems/docs/pull/111

**Comment by LakshmiLavanyaKasturi** [comment]
Done.
